from pathlib import Path
CODE='adfe37a3f68a545635f173c22d4710eacde86e74'
def once(path,old,new):
 p=Path(path); t=p.read_text(encoding='utf-8')
 if t.count(old)!=1: raise SystemExit(f'{path}: state transition mismatch')
 p.write_text(t.replace(old,new,1),encoding='utf-8')
once('state/progress.md','D4-B is merged and verified on `d60a3be993c76b59292cf27ee66bcbe856669fc4`. PR-head Level-5 run `31716610699` and merged-head Level-5 run `31717705331` both passed; implementation head and merge commit are content-identical. D4-C is authorized next.\n\nD4-D, D5 and release readiness remain gated.',f'D4-B remains closed. D4-C implementation code commit `{CODE}` adds the redacted Settings status, read-only Settings presentation and two fixed packaged update-failure outcomes. Focused Python tests, frontend tests/build and lifecycle integrity passed before publication.\n\nExact published-head/package verification and lifecycle closure are still required. D4-D, D5 and release readiness remain gated.')
once('state/handoff.md','- D4-B is DONE — merged, exact-head/exact-package verified and lifecycle-closed.','- D4-B is DONE — merged, exact-head/exact-package verified and lifecycle-closed.\n- D4-C is IMPLEMENTED — exact-head/exact-package verification and lifecycle closure pending.')
once('state/handoff.md','## D4-B closed handoff / D4-C next','## D4-C implementation handoff')
once('state/handoff.md','D4-C may now be implemented only within its bounded user-facing status/failure UX scope. If it requires a protected Restore production change, new update authority, D4-D behavior or release/distribution work, stop rather than widening D4-C.',f'D4-C code is implemented at `{CODE}` through the existing Settings binding and packaged entrypoint seams. Protected `launcher/runtime.py` and `frontend/src/main.ts` remain unchanged. Verify this branch exactly; do not widen into D4-D, release work or Restore.')
once('state/change-requests.md','Status: **ACCEPTED — D4-A/B CLOSED; D4-C AUTHORIZED NEXT**.','Status: **ACCEPTED — D4-A/B CLOSED; D4-C IMPLEMENTED, VERIFICATION PENDING**.')
once('state/change-requests.md','D4-A and D4-B are closed. D4-B provides staged migrations, verified backup, atomic canonical publication, durable external UpdateLog and interruption reconciliation. D4-C update status/failure UX is authorized next but remains unimplemented; D4-D remains unauthorized.',f'D4-A and D4-B are closed. D4-C implementation code commit `{CODE}` adds only the bounded read-only status and packaged failure UX authorized by CR-013. D4-C is not yet exact-head/exact-package verified or lifecycle-closed; D4-D remains unauthorized.')
once('state/change-requests.md','D4-A closure remains satisfied. D4-B closure conditions are satisfied on verified implementation head `8688fa3dba87205b4b4626ebab2902262fd4cd24` and merged head `d60a3be993c76b59292cf27ee66bcbe856669fc4` with full Level-5 PASS evidence. D4-C alone is authorized next.','D4-A and D4-B closure remain satisfied. D4-C is implementation-complete in the current branch; only D4-C verification and lifecycle closure are authorized next. D4-D is not authorized.')
