from pathlib import Path

def once(path,old,new):
 p=Path(path); t=p.read_text(encoding='utf-8')
 if t.count(old)!=1: raise SystemExit(f'{path}: supporting doc mismatch')
 p.write_text(t.replace(old,new,1),encoding='utf-8')

once('docs/packaging.md','Status: **CURRENT — D3 IMPLEMENTED; D4-A/B CLOSED; D4-C AUTHORIZED NEXT**','Status: **CURRENT — D3 IMPLEMENTED; D4-A/B CLOSED; D4-C IMPLEMENTED, VERIFICATION PENDING**')
once('docs/packaging.md','D4 remains safe manual package replacement. D4-A supplies the closed compatibility gate; closed D4-B supplies staged migration and durable external UpdateLog on the same ordinary packaged startup path. D4-C is now authorized to add only bounded user-facing status/failure presentation.','D4 remains safe manual package replacement. D4-A supplies the closed compatibility gate; D4-B owns staged migration and UpdateLog; D4-C adds only bounded read-only status/failure presentation on top of that startup truth.')
once('docs/packaging.md','The existing Finder-visible fixed-message mechanism remains unchanged in D4-A. D4-C may later extend it with bounded update/migration failure categories. D4-A adds no technical update admin UI and no new Finder error category.','D4-C extends the existing Finder-visible fixed-message catalogue with two update outcomes only: stopped before canonical DB replacement, or completion cannot be confirmed automatically. Messages are fixed, non-technical and never interpolate exception text, paths or migration internals.')
once('docs/deployment.md','D4-B closure authorizes D4-C only. D4-D and D5 remain unauthorized. No signing, notarization, DMG, App Store, release channel, updater downloader, cloud deployment or cloud sync is authorized by CR-013.','D4-C adds no deployment topology: Settings uses the existing local API and packaged failures use the existing package entrypoint. D4-D and D5 remain unauthorized; no release/distribution or cloud work is authorized.')
once('docs/update-guide.md','Статус: **D4-A закрыт; D4-B закрыт и проверен; D4-C авторизован следующим, но пользовательский update UX ещё не реализован**.','Статус: **D4-A и D4-B закрыты; D4-C реализован, но exact-head/exact-package проверка и lifecycle closure ещё не завершены**.')
once('docs/update-guide.md','Этот файл пока **не является инструкцией о готовом обновлении продукта**. D4-A закрыт; D4-B закрыт; безопасный staged migration + durable UpdateLog прошли exact-head/exact-package проверку. D4-C теперь авторизован следующим, но пользовательский update status/failure UX ещё не реализован; D4-D остаётся неавторизован.','Этот файл пока **не является инструкцией о готовом обновлении продукта**. D4-A и D4-B закрыты; D4-C уже реализует понятный read-only статус и фиксированные packaged failure-сообщения, но его exact-head/exact-package проверка и lifecycle closure ещё не завершены. D4-D остаётся неавторизован.')
