import test from 'node:test';
import assert from 'node:assert/strict';
import { ALERT_ACTION_UNCERTAIN_MESSAGE, ALERT_INVALID_RESPONSE_MESSAGE, ALERT_MUTATION_UNCERTAIN_MESSAGE, ALERT_REGENERATION_REFRESH_WARNING_ANNOUNCEMENT, AlertsFeedbackLifecycle, alertsPresentation, bindAlertsActionControls, filterDisplayedAlerts, selectAlertFocusTarget, transitionAlertsRouteOwnership } from '../dist-tests/alerts-feedback/alerts-feedback.js';
const f={status:'open',type:'',search:''};
const a=(id,status='open',type='low_ingredient_stock',m='alpha')=>({id,alert_key:`k${id}`,type,severity:'warning',message:m,related_entity_type:'ingredient',related_entity_id:id,recommended_action:`act ${m}`,status,created_at:'2026',updated_at:'2026',resolved_at:null,dismissed_at:null});
function seeded(items=[a(1)], filters=f){const c=new AlertsFeedbackLifecycle();c.enterRoute();const r=c.startRead('initial',filters);assert.equal(r.accepted,true);assert.equal(c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,items).accepted,true);return c;}

test('initial non-empty success commits a readable snapshot',()=>{const c=new AlertsFeedbackLifecycle();c.enterRoute();const r=c.startRead('initial',f);const done=c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(1)]);assert.equal(done.accepted,true);assert.equal(done.announcement,'none');assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);assert.equal(alertsPresentation(c.state).canShowSnapshot,true);});
test('initial valid-empty success is a successful snapshot, not an error',()=>{const c=new AlertsFeedbackLifecycle();c.enterRoute();const r=c.startRead('initial',f);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[]);const view=alertsPresentation(c.state);assert.equal(c.state.snapshot.loaded,true);assert.equal(c.state.snapshot.items.length,0);assert.equal(view.initialError,false);assert.equal(view.canShowSnapshot,true);});
test('initial failure without snapshot shows initial error and no false snapshot',()=>{const c=new AlertsFeedbackLifecycle();c.enterRoute();const r=c.startRead('initial',f);const done=c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(done.announcement,'assertive');assert.equal(c.state.snapshot,null);assert.equal(alertsPresentation(c.state).initialError,true);});
test('manual refresh success replaces the snapshot and announces politely',()=>{const c=seeded([a(1)]);const r=c.startRead('refresh',f);const done=c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2)]);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);assert.equal(done.announcement,'polite');assert.equal(c.state.feedback.message,'Список алертов обновлён.');});
test('refresh failure preserves non-empty data and exposes stale warning',()=>{const c=seeded([a(1)]);const r=c.startRead('refresh',f);const done=c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);assert.equal(done.announcement,'assertive');assert.match(alertsPresentation(c.state).staleWarning,/устаревшими/);});
test('refresh failure preserves a valid empty snapshot',()=>{const c=seeded([]);const r=c.startRead('refresh',f);c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(c.state.snapshot.items.length,0);assert.equal(alertsPresentation(c.state).canShowSnapshot,true);});
test('duplicate read is rejected without changing owner',()=>{const c=seeded([a(1)]);const r=c.startRead('refresh',f);const duplicate=c.startRead('refresh',f);assert.equal(duplicate.accepted,false);assert.equal(c.state.read.id,r.requestId);});
test('stale read success and stale read failure are rejected',()=>{const c=seeded([a(1)]);const r=c.startRead('refresh',f);assert.equal(c.finishReadSuccess(r.requestId+1,r.routeGeneration,r.filters,[a(2)]).accepted,false);assert.equal(c.finishReadFailure(r.requestId+1,r.routeGeneration,r.filters).accepted,false);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);assert.equal(c.state.read.id,r.requestId);});
test('filter success commits only the captured filter snapshot',()=>{const c=seeded([a(1,'open')]);const nf={status:'resolved',type:'',search:''};const r=c.startRead('filter',nf);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2,'resolved')]);assert.equal(c.state.snapshot.filters.status,'resolved');assert.deepEqual(c.state.snapshot.items.map(x=>x.status),['resolved']);});
test('failed status filter does not relabel old displayed data',()=>{const c=seeded([a(1,'open')]);const r=c.startRead('filter',{status:'resolved',type:'',search:''});c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(c.state.snapshot.filters.status,'open');assert.equal(alertsPresentation(c.state).appliedFilters.status,'open');});
test('failed type filter does not relabel old displayed data',()=>{const c=seeded([a(1,'open','low_ingredient_stock')]);const r=c.startRead('filter',{status:'open',type:'ingredient_expired',search:''});c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(c.state.snapshot.filters.type,'');assert.equal(alertsPresentation(c.state).appliedFilters.type,'');});
test('old-filter response is rejected when filters do not match captured owner',()=>{const c=seeded([a(1)]);const r=c.startRead('filter',{status:'resolved',type:'',search:''});const done=c.finishReadSuccess(r.requestId,r.routeGeneration,{status:'open',type:'',search:''},[a(2)]);assert.equal(done.accepted,false);assert.equal(c.state.snapshot.filters.status,'open');});
test('local search operates only on the displayed snapshot',()=>{const c=seeded([a(1,'open','','needle'),a(2,'open','','hay')]);c.setSearch('needle');assert.deepEqual(filterDisplayedAlerts(c.state.snapshot.items,c.state.search,x=>x.message).map(x=>x.id),[1]);assert.equal(alertsPresentation(c.state).appliedFilters.status,'open');});
test('regeneration success records counters without inventing rows',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');const done=c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:2,resolved_count:3,open_count:4});assert.equal(done.announcement,'polite');assert.equal(c.state.lastGeneration.open_count,4);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);});
test('regeneration failure or uncertainty preserves snapshot and uses truthful copy',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');const done=c.finishMutationFailure(m.requestId,m.routeGeneration);assert.equal(done.message,ALERT_MUTATION_UNCERTAIN_MESSAGE);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);});
test('regeneration success plus refresh success replaces list once',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:0,updated_count:0,resolved_count:0,open_count:1});const r=c.startRead('regeneration-refresh',f);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2)]);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);assert.equal(c.state.feedback.mutationError,'');});
test('regeneration success plus refresh failure remains success plus warning with assertive announcement text',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:0,resolved_count:0,open_count:1});const r=c.startRead('regeneration-refresh',f);const refresh=c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);assert.match(c.state.feedback.message,/Алерты обновлены/);assert.match(c.state.feedback.refreshWarning,/Не удалось обновить список/);assert.equal(c.state.feedback.mutationError,'');assert.equal(refresh.announcement,'assertive');assert.match(ALERT_REGENERATION_REFRESH_WARNING_ANNOUNCEMENT,/список не удалось перечитать/);});
test('resolve under open removes the alert from the visible snapshot',()=>{const c=seeded([a(1),a(2)]);const m=c.startMutation('resolve',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(1,'resolved'));assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('dismiss under open removes the alert from the visible snapshot',()=>{const c=seeded([a(1),a(2)]);const m=c.startMutation('dismiss',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'dismiss',a(1,'dismissed'));assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('resolve under all keeps the authoritative returned alert',()=>{const c=seeded([a(1)],{status:'all',type:'',search:''});const m=c.startMutation('resolve',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(1,'resolved'));assert.equal(c.state.snapshot.items[0].status,'resolved');});
test('dismiss under all keeps the authoritative returned alert',()=>{const c=seeded([a(1)],{status:'all',type:'',search:''});const m=c.startMutation('dismiss',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'dismiss',a(1,'dismissed'));assert.equal(c.state.snapshot.items[0].status,'dismissed');});
test('type-filter behavior is respected by authoritative mutation responses',()=>{const c=seeded([a(1,'open','low_ingredient_stock')],{status:'resolved',type:'ingredient_expired',search:''});const m=c.startMutation('resolve',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(1,'resolved','low_ingredient_stock'));assert.equal(c.state.snapshot.items.length,0);assert.equal(c.state.snapshot.filters.type,'ingredient_expired');});
test('duplicate mutation is rejected while a mutation owns the route',()=>{const c=seeded([a(1)]);const m=c.startMutation('resolve',c.state.routeGeneration,1);assert.equal(m.accepted,true);assert.equal(c.startMutation('dismiss',c.state.routeGeneration,1).accepted,false);assert.equal(alertsPresentation(c.state).controlsDisabled,true);});
test('stale mutation response cannot clear a newer owner',()=>{const c=seeded([a(1),a(2)]);const stale=c.startMutation('resolve',c.state.routeGeneration,1);c.state.mutation=null;const newer=c.startMutation('dismiss',c.state.routeGeneration,2);const done=c.applyMutationResponse(stale.requestId,stale.routeGeneration,1,'resolve',a(1,'resolved'));assert.equal(done.accepted,false);assert.equal(c.state.mutation.id,newer.requestId);});
test('wrong-alert DTO clears current owner, preserves snapshot and asks to refresh',()=>{const c=seeded([a(1),a(2)]);const m=c.startMutation('resolve',c.state.routeGeneration,1);const done=c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(2,'resolved'));assert.equal(done.accepted,true);assert.equal(done.announcement,'assertive');assert.equal(c.state.mutation,null);assert.deepEqual(c.state.snapshot.items.map(x=>x.status),['open','open']);assert.equal(c.state.feedback.mutationError,ALERT_INVALID_RESPONSE_MESSAGE);});
test('route leave suppresses presentation while allowing current data to commit silently',()=>{const c=new AlertsFeedbackLifecycle();const g=c.enterRoute();const r=c.startRead('initial',f,g);c.leaveRoute();const done=c.finishReadSuccess(r.requestId,g,r.filters,[a(1)]);assert.equal(done.present,false);assert.equal(c.state.snapshot.items.length,1);});
test('route leave and return creates a new generation and old callback cannot present',()=>{const c=new AlertsFeedbackLifecycle();const g1=c.enterRoute();const r=c.startRead('initial',f,g1);c.leaveRoute();const g2=c.enterRoute();const done=c.finishReadSuccess(r.requestId,g1,r.filters,[a(1)]);assert.notEqual(g1,g2);assert.equal(done.present,false);});
test('navigation adapter enters and leaves Alerts exactly on route boundary changes',()=>{const calls=[];const l={enterRoute(){calls.push('enter');return calls.length;},leaveRoute(){calls.push('leave');return calls.length;}};assert.equal(transitionAlertsRouteOwnership(l,'Главная','Алерты'),'entered');assert.equal(transitionAlertsRouteOwnership(l,'Алерты','Алерты'),'unchanged');assert.equal(transitionAlertsRouteOwnership(l,'Алерты','Заказы'),'left');assert.deepEqual(calls,['enter','leave']);});
test('busy presentation disables server controls but keeps local search explicit',()=>{const c=seeded([a(1)]);const r=c.startRead('refresh',f);let v=alertsPresentation(c.state);assert.equal(v.controlsDisabled,true);assert.equal(v.workspaceBusy,true);assert.equal(v.searchEnabled,true);c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);const m=c.startMutation('resolve',c.state.routeGeneration,1);v=alertsPresentation(c.state);assert.equal(v.resolveCopy,'Отмечаем…');assert.equal(v.controlsDisabled,true);});
test('final focus after resolve falls back to list/main when open card disappears',()=>{assert.equal(selectAlertFocusTarget(true,'alert-1-resolve',1,[{key:'alert-1-resolve',kind:'previous',enabled:true,attached:false},{key:'alert-1-heading',kind:'alert-heading',enabled:true,attached:false},{key:'alerts-list-region',kind:'list-region',enabled:true,attached:true},{key:'alerts-main-heading',kind:'main-heading',enabled:true,attached:true}]),'alerts-list-region');});
test('final focus after dismiss under all can return to affected heading',()=>{assert.equal(selectAlertFocusTarget(true,'alert-1-dismiss',1,[{key:'alert-1-dismiss',kind:'previous',enabled:true,attached:false},{key:'alert-1-heading',kind:'alert-heading',enabled:true,attached:true}]),'alert-1-heading');});
test('focus selection skips disabled previous controls and supports main-heading fallback',()=>{assert.equal(selectAlertFocusTarget(true,'prev',1,[{key:'prev',kind:'previous',enabled:false,attached:true},{key:'live',kind:'live-region',enabled:true,attached:true},{key:'alerts-main-heading',kind:'main-heading',enabled:true,attached:true}]),'alerts-main-heading');assert.equal(selectAlertFocusTarget(false,null,1,[{key:'alerts-main-heading',kind:'main-heading',enabled:true,attached:true}]),null);});


function reconcile(c, g, items, kind='refresh'){const r=c.startReconciliationRead(kind,c.displayedFilters(),g);assert.equal(r.accepted,true);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,items);return r;}

test('leave and return during initial load clears old read owner and allows fresh load',()=>{const c=new AlertsFeedbackLifecycle();const g1=c.enterRoute();const old=c.startRead('initial',f,g1);c.leaveRoute();const g2=c.enterRoute();assert.equal(c.state.read,null);assert.equal(c.hasPendingReconciliation(),true);const fresh=c.startReconciliationRead('initial',f,g2);assert.equal(fresh.accepted,true);assert.equal(c.finishReadSuccess(old.requestId,g1,old.filters,[a(1)]).accepted,false);c.finishReadSuccess(fresh.requestId,fresh.routeGeneration,fresh.filters,[a(2)]);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('leave and return during manual refresh clears busy state and reconciles with one accepted GET',()=>{const c=seeded([a(1)]);const old=c.startRead('refresh',f);c.leaveRoute();const g2=c.enterRoute();const fresh=reconcile(c,g2,[a(3)]);assert.equal(fresh.accepted,true);assert.equal(c.finishReadFailure(old.requestId,old.routeGeneration,old.filters).accepted,false);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[3]);});
test('leave and return during resolve waits for exact settlement before reconciliation GET',()=>{const c=seeded([a(1)]);const old=c.startMutation('resolve',c.state.routeGeneration,1);c.leaveRoute();const g2=c.enterRoute();assert.equal(c.state.detachedMutation?.requestId,old.requestId);assert.equal(c.startReconciliationRead('refresh',f,g2).accepted,false);assert.equal(c.settleDetachedActionSuccess(old.requestId+1,'resolve',1,a(1,'resolved')).accepted,false);assert.equal(c.state.detachedMutation?.requestId,old.requestId);const settled=c.settleDetachedActionSuccess(old.requestId,'resolve',1,a(1,'resolved'));assert.equal(settled.settledDetached,true);const fresh=reconcile(c,g2,[a(1,'resolved')]);assert.equal(fresh.accepted,true);assert.equal(c.state.snapshot.items[0].status,'resolved');assert.equal(alertsPresentation(c.state).controlsDisabled,false);});
test('leave and return during dismiss waits for exact settlement and leaves busy state',()=>{const c=seeded([a(1)]);const old=c.startMutation('dismiss',c.state.routeGeneration,1);c.leaveRoute();const g2=c.enterRoute();assert.equal(c.startReconciliationRead('refresh',f,g2).accepted,false);assert.equal(c.settleDetachedMutationFailure(old.requestId,'resolve',1).accepted,false);assert.equal(c.state.detachedMutation?.kind,'dismiss');c.settleDetachedActionSuccess(old.requestId,'dismiss',1,a(1,'dismissed'));reconcile(c,g2,[]);assert.equal(c.state.snapshot.items.length,0);assert.equal(alertsPresentation(c.state).workspaceBusy,false);});
test('leave and return during regeneration POST records counters and uses one reconciliation GET',()=>{const c=seeded([a(1)]);const old=c.startMutation('regenerate',c.state.routeGeneration);c.leaveRoute();const g2=c.enterRoute();assert.equal(c.startReconciliationRead('refresh',f,g2).accepted,false);const settled=c.settleDetachedRegenerationSuccess(old.requestId,{created_count:1,updated_count:2,resolved_count:3,open_count:4});assert.equal(settled.settledDetached,true);assert.equal(c.state.lastGeneration?.open_count,4);reconcile(c,g2,[a(2)]);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('old operation success or failure after return cannot present and new visit leaves busy state',()=>{const c=seeded([a(1)]);const old=c.startRead('refresh',f);c.leaveRoute();const g2=c.enterRoute();const fresh=c.startReconciliationRead('refresh',f,g2);c.finishReadSuccess(fresh.requestId,fresh.routeGeneration,fresh.filters,[a(2)]);assert.equal(c.finishReadSuccess(old.requestId,old.routeGeneration,old.filters,[a(3)]).accepted,false);assert.equal(c.finishReadFailure(old.requestId,old.routeGeneration,old.filters).accepted,false);assert.equal(alertsPresentation(c.state).controlsDisabled,false);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('leaving during regeneration follow-up success suppresses final presentation but records regeneration',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');const mutation=c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:0,resolved_count:0,open_count:1});const r=c.startRead('regeneration-refresh',f);c.leaveRoute();const refresh=c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2)]);assert.equal(mutation.present,true);assert.equal(refresh.present,false);assert.equal(c.state.lastGeneration.created_count,1);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('leaving during regeneration follow-up failure suppresses late warning presentation',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:0,resolved_count:0,open_count:1});const r=c.startRead('regeneration-refresh',f);c.leaveRoute();const refresh=c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(refresh.present,false);assert.equal(refresh.announcement,'none');assert.equal(c.state.lastGeneration.created_count,1);});
test('leave and return during regeneration follow-up requires current-visit reconciliation',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:0,resolved_count:0,open_count:1});const oldRefresh=c.startRead('regeneration-refresh',f);c.leaveRoute();const g2=c.enterRoute();reconcile(c,g2,[a(3)]);assert.equal(c.finishReadSuccess(oldRefresh.requestId,oldRefresh.routeGeneration,oldRefresh.filters,[a(2)]).accepted,false);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[3]);});
test('busy presentation applies disabled reset state to empty snapshots',()=>{const c=seeded([],{status:'resolved',type:'',search:''});const r=c.startRead('refresh',c.displayedFilters());const view=alertsPresentation(c.state);assert.equal(view.controlsDisabled,true);assert.equal(c.state.snapshot.items.length,0);assert.equal(r.accepted,true);});

test('all-control binding wires two reload controls once each',()=>{let calls=0;const buttons=[{n:0,addEventListener(t,fn){this.fn=fn;this.n++;}},{n:0,addEventListener(t,fn){this.fn=fn;this.n++;}}];assert.equal(bindAlertsActionControls({querySelectorAll:()=>buttons},'[data-action="reload-alerts"]',()=>calls++),2);buttons.forEach(b=>{assert.equal(b.n,1);b.fn();});assert.equal(calls,2);});
test('zero-control binding is safe',()=>{assert.equal(bindAlertsActionControls({querySelectorAll:()=>[]},'[data-action="reload-alerts"]',()=>{}),0);});

test('wrong detached callback identity cannot settle or start reconciliation',()=>{const c=seeded([a(1)]);const m=c.startMutation('resolve',c.state.routeGeneration,1);c.leaveRoute();assert.equal(c.settleDetachedActionSuccess(m.requestId+1,'resolve',1,a(1,'resolved')).accepted,false);assert.equal(c.settleDetachedActionSuccess(m.requestId,'dismiss',1,a(1,'dismissed')).accepted,false);assert.equal(c.settleDetachedActionSuccess(m.requestId,'resolve',2,a(2,'resolved')).accepted,false);assert.equal(c.state.detachedMutation?.requestId,m.requestId);assert.equal(c.hasPendingReconciliation(),false);});
test('matching detached invalid DTO settles without updating another alert',()=>{const c=seeded([a(1),a(2)]);const m=c.startMutation('resolve',c.state.routeGeneration,1);c.leaveRoute();const settled=c.settleDetachedActionSuccess(m.requestId,'resolve',1,a(2,'resolved'));assert.equal(settled.settledDetached,true);assert.equal(c.state.detachedMutation,null);assert.deepEqual(c.state.snapshot.items.map(x=>x.status),['open','open']);assert.equal(c.hasPendingReconciliation(),true);});
test('duplicate detached callback is idempotently ignored without second obligation',()=>{const c=seeded([a(1)]);const m=c.startMutation('resolve',c.state.routeGeneration,1);c.leaveRoute();assert.equal(c.settleDetachedActionSuccess(m.requestId,'resolve',1,a(1,'resolved')).settledDetached,true);assert.equal(c.settleDetachedActionSuccess(m.requestId,'resolve',1,a(1,'resolved')).accepted,false);const g=c.enterRoute();const r=reconcile(c,g,[a(1,'resolved')]);assert.equal(r.accepted,true);assert.equal(c.startReconciliationRead('refresh',f,g).accepted,false);});
test('read success while away is ignored for presentation and read failure while away requires next reconciliation',()=>{let c=seeded([a(1)]);let r=c.startRead('refresh',f);c.leaveRoute();let done=c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2)]);assert.equal(done.present,false);c=seeded([a(1)]);r=c.startRead('refresh',f);c.leaveRoute();done=c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(done.present,false);assert.equal(c.hasPendingReconciliation(),true);});
test('lossless reconciliation remains pending when read cannot start while busy',()=>{const c=seeded([a(1)]);const r=c.startRead('refresh',f);c.state.reentryNeedsReconcile=true;assert.equal(c.startReconciliationRead('refresh',f).accepted,false);assert.equal(c.hasPendingReconciliation(),true);c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);const accepted=c.startReconciliationRead('refresh',f);assert.equal(accepted.accepted,true);assert.equal(c.hasPendingReconciliation(),false);assert.equal(c.startReconciliationRead('refresh',f).accepted,false);});
test('stale follow-up after completed reconciliation does not recreate obligation or GET',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:0,resolved_count:0,open_count:1});const old=c.startRead('regeneration-refresh',f);c.leaveRoute();const g=c.enterRoute();const current=reconcile(c,g,[a(3)]);assert.equal(current.accepted,true);assert.equal(c.hasPendingReconciliation(),false);assert.equal(c.finishReadSuccess(old.requestId,old.routeGeneration,old.filters,[a(2)]).accepted,false);assert.equal(c.hasPendingReconciliation(),false);});

function deferred(){let resolve,reject;const promise=new Promise((res,rej)=>{resolve=res;reject=rej;});return{promise,resolve,reject};}
function asyncHarness(items=[a(1)]){const c=seeded(items);const calls={get:0,resolve:0,dismiss:0,regenerate:0,announce:0,focus:0,render:0};let active=true;const pending=[];function startReconcile(){if(!active)return false;const r=c.startReconciliationRead('refresh',c.displayedFilters(),c.state.routeGeneration);if(!r.accepted)return false;calls.get++;pending.push(r);return true;}function finishGet(items){const r=pending.shift();c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,items);}async function action(kind,id,d){const s=c.startMutation(kind,c.state.routeGeneration,id,`alert-${id}-${kind}`);calls[kind]++;try{const response=await d.promise;const owned=c.applyMutationResponse(s.requestId,s.routeGeneration,id,kind,response);if(!owned.accepted){const detached=c.settleDetachedActionSuccess(s.requestId,kind,id,response);if(detached.settledDetached)startReconcile();return;}if(owned.present){calls.render++;calls.announce++;}}catch{const owned=c.finishMutationFailure(s.requestId,s.routeGeneration);if(!owned.accepted){const detached=c.settleDetachedMutationFailure(s.requestId,kind,id);if(detached.settledDetached)startReconcile();return;}if(owned.present){calls.render++;calls.announce++;}}}async function regeneration(d){const s=c.startMutation('regenerate',c.state.routeGeneration);calls.regenerate++;try{const response=await d.promise;const owned=c.finishRegenerationSuccess(s.requestId,s.routeGeneration,response);if(!owned.accepted){const detached=c.settleDetachedRegenerationSuccess(s.requestId,response);if(detached.settledDetached)startReconcile();return;}if(owned.present){const r=c.startRead('regeneration-refresh',c.displayedFilters(),s.routeGeneration);assert.equal(r.accepted,true);calls.get++;pending.push(r);}}catch{const owned=c.finishMutationFailure(s.requestId,s.routeGeneration);if(!owned.accepted){const detached=c.settleDetachedMutationFailure(s.requestId,'regenerate',null);if(detached.settledDetached)startReconcile();}}}function leave(){active=false;c.leaveRoute();}function enter(){active=true;return c.enterRoute();}return{c,calls,startReconcile,finishGet,action,regeneration,leave,enter};}

test('async stale read cannot settle detached resolve before exact POST settles',async()=>{const h=asyncHarness([a(1)]);const old=h.c.startRead('regeneration-refresh',f);h.c.leaveRoute();const g=h.c.enterRoute();reconcile(h.c,g,[a(1)]);const d=deferred();const p=h.action('resolve',1,d);h.c.leaveRoute();h.c.enterRoute();assert.equal(h.c.finishReadSuccess(old.requestId,old.routeGeneration,old.filters,[a(9)]).accepted,false);assert.equal(h.c.state.detachedMutation?.kind,'resolve');assert.equal(h.calls.get,0);d.resolve(a(1,'resolved'));await p;assert.equal(h.calls.resolve,1);assert.equal(h.calls.get,1);h.finishGet([a(1,'resolved')]);assert.equal(h.c.state.snapshot.items[0].status,'resolved');});
test('async stale read cannot settle detached dismiss before exact POST settles',async()=>{const h=asyncHarness([a(1)]);const old=h.c.startRead('regeneration-refresh',f);h.c.leaveRoute();const g=h.c.enterRoute();reconcile(h.c,g,[a(1)]);const d=deferred();const p=h.action('dismiss',1,d);h.c.leaveRoute();h.c.enterRoute();h.c.finishReadFailure(old.requestId,old.routeGeneration,old.filters);assert.equal(h.c.state.detachedMutation?.kind,'dismiss');assert.equal(h.calls.get,0);d.resolve(a(1,'dismissed'));await p;assert.equal(h.calls.dismiss,1);assert.equal(h.calls.get,1);});
test('async regeneration chooses detached reconciliation instead of ordinary follow-up after route loss',async()=>{const h=asyncHarness([a(1)]);const d=deferred();const p=h.regeneration(d);h.c.leaveRoute();h.c.enterRoute();assert.equal(alertsPresentation(h.c.state).workspaceBusy,true);assert.equal(h.calls.get,0);d.resolve({created_count:5,updated_count:4,resolved_count:3,open_count:2});await p;assert.equal(h.calls.regenerate,1);assert.equal(h.c.state.lastGeneration.open_count,2);assert.equal(h.calls.get,1);h.finishGet([a(2)]);assert.deepEqual(h.c.state.snapshot.items.map(x=>x.id),[2]);});

test('async stale read cannot settle detached regeneration before exact POST settles',async()=>{const h=asyncHarness([a(1)]);const old=h.c.startRead('regeneration-refresh',f);h.c.leaveRoute();const g=h.c.enterRoute();reconcile(h.c,g,[a(1)]);const d=deferred();const p=h.regeneration(d);h.c.leaveRoute();h.c.enterRoute();h.c.finishReadSuccess(old.requestId,old.routeGeneration,old.filters,[a(9)]);assert.equal(h.c.state.detachedMutation?.kind,'regenerate');assert.equal(h.calls.get,0);d.resolve({created_count:1,updated_count:1,resolved_count:0,open_count:1});await p;assert.equal(h.calls.regenerate,1);assert.equal(h.calls.get,1);});
test('async regeneration settling while away records counters and waits for route entry GET',async()=>{const h=asyncHarness([a(1)]);const d=deferred();const p=h.regeneration(d);h.leave();d.resolve({created_count:7,updated_count:6,resolved_count:5,open_count:4});await p;assert.equal(h.calls.regenerate,1);assert.equal(h.calls.get,0);assert.equal(h.c.state.lastGeneration.created_count,7);h.enter();assert.equal(h.startReconcile(),true);assert.equal(h.calls.get,1);});
test('async owned regeneration starts exactly one ordinary follow-up GET and no detached obligation',async()=>{const h=asyncHarness([a(1)]);const d=deferred();const p=h.regeneration(d);d.resolve({created_count:1,updated_count:0,resolved_count:0,open_count:1});await p;assert.equal(h.calls.regenerate,1);assert.equal(h.calls.get,1);assert.equal(h.c.state.detachedMutation,null);assert.equal(h.c.hasPendingReconciliation(),false);});
