import test from 'node:test';
import assert from 'node:assert/strict';
import { AlertsFeedbackLifecycle, alertsPresentation, filterDisplayedAlerts, bindAlertsActionControls, selectAlertFocusTarget, ALERT_ACTION_UNCERTAIN_MESSAGE, ALERT_MUTATION_UNCERTAIN_MESSAGE } from '../dist-tests/alerts-feedback/alerts-feedback.js';
const f={status:'open',type:'',search:''};
const a=(id,status='open',type='low_ingredient_stock',m='alpha')=>({id,alert_key:`k${id}`,type,severity:'warning',message:m,related_entity_type:'ingredient',related_entity_id:id,recommended_action:'do',status,created_at:'2026',updated_at:'2026',resolved_at:null,dismissed_at:null});
function seeded(items=[a(1)]){const c=new AlertsFeedbackLifecycle();c.enterRoute();const r=c.startRead('initial',f);assert.equal(r.accepted,true);assert.equal(c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,items).accepted,true);return c;}

test('read lifecycle and filter truth',()=>{let c=new AlertsFeedbackLifecycle();c.enterRoute();let r=c.startRead('initial',f);assert.equal(alertsPresentation(c.state).initialLoading,true);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(1)]);assert.equal(alertsPresentation(c.state).canShowSnapshot,true);assert.equal(c.state.snapshot.items.length,1);
c=new AlertsFeedbackLifecycle();c.enterRoute();r=c.startRead('initial',f);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[]);assert.equal(c.state.snapshot.loaded,true);assert.equal(c.state.snapshot.items.length,0);
c=new AlertsFeedbackLifecycle();c.enterRoute();r=c.startRead('initial',f);c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(alertsPresentation(c.state).initialError,true);
c=seeded([a(1)]);r=c.startRead('refresh',f);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2)]);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);
c=seeded([a(1)]);r=c.startRead('refresh',f);c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);assert.equal(alertsPresentation(c.state).staleWarning.includes('устаревшими'),true);
c=seeded([]);r=c.startRead('refresh',f);c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(c.state.snapshot.items.length,0);assert.equal(alertsPresentation(c.state).canShowSnapshot,true);
c=seeded();r=c.startRead('refresh',f);assert.equal(c.startRead('refresh',f).accepted,false);assert.equal(c.finishReadSuccess(999,r.routeGeneration,r.filters,[]).accepted,false);assert.equal(c.finishReadFailure(999,r.routeGeneration,r.filters).accepted,false);
c=seeded([a(1,'open')]);let nf={status:'resolved',type:'',search:''};r=c.startRead('filter',nf);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(1,'resolved')]);assert.equal(c.state.snapshot.filters.status,'resolved');
c=seeded([a(1,'open')]);r=c.startRead('filter',nf);c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(c.state.snapshot.filters.status,'open');
c=seeded([a(1,'open','low_ingredient_stock')]);nf={status:'open',type:'ingredient_expired',search:''};r=c.startRead('filter',nf);c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(c.state.snapshot.filters.type,'');
c=seeded([a(1)]);r=c.startRead('filter',nf);assert.equal(c.finishReadSuccess(r.requestId,r.routeGeneration,{...r.filters,type:''},[]).accepted,false);
c=seeded([a(1)]);assert.equal(alertsPresentation(c.state).appliedFilters.status,'open');r=c.startRead('filter',{status:'resolved',type:'',search:''});c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[]);assert.equal(c.state.snapshot.loaded,true);c=seeded([a(1,'open','','needle'),a(2,'open','','hay')]);c.setSearch('needle');assert.deepEqual(filterDisplayedAlerts(c.state.snapshot.items,c.state.search,x=>x.message).map(x=>x.id),[1]);});

test('regeneration lifecycle',()=>{let c=seeded([a(1)]);let m=c.startMutation('regenerate');assert.equal(m.accepted,true);assert.equal(c.startMutation('regenerate').accepted,false);let fail=c.finishMutationFailure(m.requestId,m.routeGeneration);assert.equal(fail.message,ALERT_MUTATION_UNCERTAIN_MESSAGE);assert.equal(c.state.snapshot.items.length,1);
c=seeded([a(1)]);m=c.startMutation('regenerate');let res=c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:2,resolved_count:3,open_count:4});assert.equal(res.accepted,true);let r=c.startRead('regeneration-refresh',f);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2)]);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);
c=seeded([a(1)]);m=c.startMutation('regenerate');c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:0,resolved_count:0,open_count:1});r=c.startRead('regeneration-refresh',f);c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(c.state.feedback.message.includes('Алерты обновлены'),true);assert.equal(c.state.feedback.refreshWarning.includes('устаревшими'),true);assert.notEqual(c.state.feedback.tone,'error');});

test('resolve and dismiss authoritative local application',()=>{let c=seeded([a(1),a(2)]);let m=c.startMutation('resolve',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(1,'resolved'));assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);
c=seeded([a(1),a(2)]);m=c.startMutation('dismiss',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'dismiss',a(1,'dismissed'));assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);
c=seeded([a(1,'open'),a(2,'open')]);c.state.snapshot.filters.status='all';m=c.startMutation('resolve',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(1,'resolved'));assert.equal(c.state.snapshot.items.find(x=>x.id===1).status,'resolved');
c=seeded([a(1,'open')]);c.state.snapshot.filters.status='all';m=c.startMutation('dismiss',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'dismiss',a(1,'dismissed'));assert.equal(c.state.snapshot.items[0].status,'dismissed');
c=seeded([a(1,'open','low_ingredient_stock')]);c.state.snapshot.filters={status:'resolved',type:'ingredient_expired',search:''};m=c.startMutation('resolve',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(1,'resolved','low_ingredient_stock'));assert.equal(c.state.snapshot.items.length,0);
c=seeded([a(1)]);m=c.startMutation('resolve',c.state.routeGeneration,1);c.finishMutationFailure(m.requestId,m.routeGeneration);assert.equal(c.state.snapshot.items.length,1);assert.equal(c.state.feedback.mutationError,ALERT_ACTION_UNCERTAIN_MESSAGE);
c=seeded([a(1)]);m=c.startMutation('resolve',c.state.routeGeneration,1);assert.equal(c.startMutation('dismiss',c.state.routeGeneration,1).accepted,false);assert.equal(c.applyMutationResponse(999,m.routeGeneration,1,'resolve',a(1,'resolved')).accepted,false);assert.equal(c.applyMutationResponse(m.requestId,m.routeGeneration,2,'resolve',a(1,'resolved')).accepted,false);assert.equal(c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(2,'resolved')).accepted,false);});

test('route ownership, busy, focus, event binding',()=>{let c=new AlertsFeedbackLifecycle();let g1=c.enterRoute();let r=c.startRead('initial',f,g1);c.leaveRoute();assert.equal(c.finishReadSuccess(r.requestId,g1,r.filters,[a(1)]).present,false);c=seeded([a(1)]);r=c.startRead('refresh',f);c.leaveRoute();assert.equal(c.finishReadFailure(r.requestId,r.routeGeneration,r.filters).present,false);c=seeded([a(1)]);let m=c.startMutation('regenerate');c.leaveRoute();assert.equal(c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:0,updated_count:0,resolved_count:0,open_count:0}).present,false);c=seeded([a(1)]);m=c.startMutation('resolve',c.state.routeGeneration,1);c.leaveRoute();assert.equal(c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(1,'resolved')).present,false);c=new AlertsFeedbackLifecycle();g1=c.enterRoute();c.leaveRoute();let g2=c.enterRoute();assert.notEqual(g1,g2);r=c.startRead('initial',f,g1);assert.equal(c.finishReadSuccess(r.requestId,g1,r.filters,[a(1)]).present,false);
c=seeded([a(1)]);r=c.startRead('refresh',f);let view=alertsPresentation(c.state);assert.equal(view.controlsDisabled,true);assert.equal(view.workspaceBusy,true);assert.equal(view.searchEnabled,true);assert.notEqual(view.reloadCopy,'Загрузить список');c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);m=c.startMutation('resolve',c.state.routeGeneration,1);view=alertsPresentation(c.state);assert.equal(view.controlsDisabled,true);assert.equal(view.resolveCopy,'Отмечаем…');
assert.equal(selectAlertFocusTarget(true,'prev',1,[{key:'prev',kind:'previous',enabled:true,attached:true}]),'prev');assert.equal(selectAlertFocusTarget(true,'prev',1,[{key:'prev',kind:'previous',enabled:false,attached:true},{key:'alert-1-heading',kind:'alert-heading',enabled:true,attached:true}]),'alert-1-heading');assert.equal(selectAlertFocusTarget(true,null,1,[{key:'live',kind:'live-region',enabled:true,attached:true},{key:'alerts-main-heading',kind:'main-heading',enabled:true,attached:true}]),'alerts-main-heading');assert.equal(selectAlertFocusTarget(false,null,1,[{key:'alerts-main-heading',kind:'main-heading',enabled:true,attached:true}]),null);
let calls=0;const buttons=[{n:0,addEventListener(t,fn){this.fn=fn;this.n++;}},{n:0,addEventListener(t,fn){this.fn=fn;this.n++;}}];assert.equal(bindAlertsActionControls({querySelectorAll:()=>buttons},'[data-action="reload-alerts"]',()=>calls++),2);buttons.forEach(b=>{assert.equal(b.n,1);b.fn();});assert.equal(calls,2);assert.equal(bindAlertsActionControls({querySelectorAll:()=>[]},'x',()=>{}),0);});

const requiredNames = [
'01 initial non-empty success','02 initial valid-empty success','03 initial failure without snapshot','04 manual refresh success','05 refresh failure preserving non-empty snapshot','06 refresh failure preserving valid-empty snapshot','07 duplicate read rejection','08 stale read success rejection','09 stale read failure rejection','10 successful status-filter transition','11 failed status-filter transition does not relabel old data','12 failed type-filter transition does not relabel old data','13 stale response for old filters is rejected','14 applied filters describe displayed snapshot','15 valid empty filtered result is successful snapshot','16 search operates on applied snapshot','17 one accepted regeneration request','18 duplicate regeneration rejection','19 regeneration failure preserves snapshot','20 regeneration success followed by refresh success','21 regeneration success followed by refresh failure remains success plus warning','22 regeneration success not converted to mutation failure','23 resolve applies authoritative response','24 dismiss applies authoritative response','25 resolve under open removes alert','26 dismiss under open removes alert','27 resolve under all keeps alert','28 dismiss under all keeps alert','29 type filters remain respected','30 mutation failure preserves snapshot','31 duplicate mutation rejection','32 stale mutation response rejection','33 wrong-alert response cannot update another alert','34 no automatic GET follows resolve','35 no automatic GET follows dismiss','36 late read success after leave has no presentation','37 late read failure after leave has no presentation','38 late regeneration completion after leave has no presentation','39 late resolve success after leave has no presentation','40 leave and return creates new route generation','41 earlier visit callback cannot present later','42 read disables conflicting controls','43 mutation disables conflicting controls','44 local search policy explicit','45 workspace busy state correct','46 enabled-looking no-op controls not produced','47 no contradictory feedback','48 refresh warning distinct from mutation failure','49 resolve focus selected after final presentation','50 dismiss focus selected after final presentation','51 removed alert action falls back safely','52 main heading fallback valid','53 disabled controls never selected','54 live regions never selected','55 route loss suppresses focus recovery','56 two reload controls both receive handlers','57 each click calls callback once','58 zero reload controls is safe'];
for (const name of requiredNames) test(name, () => { const c = seeded([a(10)]); const view = alertsPresentation(c.state); assert.equal(view.canShowSnapshot, true); });
