import test from 'node:test';
import assert from 'node:assert/strict';
import { ALERT_ACTION_UNCERTAIN_MESSAGE, ALERT_INVALID_RESPONSE_MESSAGE, ALERT_MUTATION_UNCERTAIN_MESSAGE, ALERT_REGENERATION_REFRESH_WARNING_ANNOUNCEMENT, AlertsFeedbackLifecycle, alertsPresentation, bindAlertsActionControls, filterDisplayedAlerts, selectAlertFocusTarget, transitionAlertsRouteOwnership } from '../dist-tests/alerts-feedback/alerts-feedback.js';
const f={status:'open',type:'',search:''};
const a=(id,status='open',type='low_ingredient_stock',m='alpha')=>({id,alert_key:`k${id}`,type,severity:'warning',message:m,related_entity_type:'ingredient',related_entity_id:id,recommended_action:`act ${m}`,status,created_at:'2026',updated_at:'2026',resolved_at:null,dismissed_at:null});
function seeded(items=[a(1)], filters=f){const c=new AlertsFeedbackLifecycle();c.enterRoute();const r=c.startRead('initial',filters);assert.equal(r.accepted,true);assert.equal(c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,items).accepted,true);return c;}

test('initial non-empty success commits a readable snapshot',()=>{const c=new AlertsFeedbackLifecycle();c.enterRoute();const r=c.startRead('initial',f);const done=c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(1)]);assert.equal(done.accepted,true);assert.equal(done.announcement,'none');assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);assert.equal(alertsPresentation(c.state).canShowSnapshot,true);});
test('initial valid-empty success is a successful snapshot, not an error',()=>{const c=new AlertsFeedbackLifecycle();c.enterRoute();const r=c.startRead('initial',f);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[]);const view=alertsPresentation(c.state);assert.equal(c.state.snapshot.loaded,true);assert.equal(c.state.snapshot.items.length,0);assert.equal(view.initialError,false);assert.equal(view.canShowSnapshot,true);});
test('initial failure without snapshot shows initial error and no false snapshot',()=>{const c=new AlertsFeedbackLifecycle();c.enterRoute();const r=c.startRead('initial',f);const done=c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(done.announcement,'assertive');assert.equal(c.state.snapshot,null);assert.equal(alertsPresentation(c.state).initialError,true);});
test('manual refresh success replaces the snapshot and announces politely',()=>{const c=seeded([a(1)]);const r=c.startRead('refresh',f);const done=c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2)]);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);assert.equal(done.announcement,'polite');assert.equal(c.state.feedback.message,'Список алертов обновлён.');});
test('refresh failure preserves non-empty data and exposes stale warning',()=>{const c=seeded([a(1)]);const r=c.startRead('refresh',f);const done=c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);assert.equal(done.announcement,'assertive');assert.match(alertsPresentation(c.state).staleWarning,/устаревшими/);});
test('refresh failure preserves a valid empty snapshot',()=>{const c=seeded([]);const r=c.startRead('refresh',f);c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(c.state.snapshot.items.length,0);assert.equal(alertsPresentation(c.state).canShowSnapshot,true);});
test('duplicate read is rejected without changing owner',()=>{const c=seeded([a(1)]);const r=c.startRead('refresh',f);const duplicate=c.startRead('refresh',f);assert.equal(duplicate.accepted,false);assert.equal(c.state.read.id,r.requestId);});
test('stale read success and stale read failure are rejected',()=>{const c=seeded([a(1)]);const r=c.startRead('refresh',f);assert.equal(c.finishReadSuccess(r.requestId+1,r.routeGeneration,r.filters,[a(2)]).accepted,false);assert.equal(c.finishReadFailure(r.requestId+1,r.routeGeneration,r.filters).accepted,false);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);assert.equal(c.state.read.id,r.requestId);});
test('filter success commits only the captured filter snapshot',()=>{const c=seeded([a(1,'open')]);const nf={status:'resolved',type:'',search:''};const r=c.startRead('filter',nf);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2,'resolved')]);assert.equal(c.state.snapshot.filters.status,'resolved');assert.deepEqual(c.state.snapshot.items.map(x=>x.status),['resolved']);});
test('failed status filter does not relabel old displayed data',()=>{const c=seeded([a(1,'open')]);const r=c.startRead('filter',{status:'resolved',type:'',search:''});c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(c.state.snapshot.filters.status,'open');assert.equal(alertsPresentation(c.state).appliedFilters.status,'open');});
test('failed type filter does not relabel old displayed data',()=>{const c=seeded([a(1,'open','low_ingredient_stock')]);const r=c.startRead('filter',{status:'open',type:'ingredient_expired',search:''});c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(c.state.snapshot.filters.type,'');assert.equal(alertsPresentation(c.state).appliedFilters.type,'');});
test('old-filter response is rejected when filters do not match captured owner',()=>{const c=seeded([a(1)]);const r=c.startRead('filter',{status:'resolved',type:'',search:''});const done=c.finishReadSuccess(r.requestId,r.routeGeneration,{status:'open',type:'',search:''},[a(2)]);assert.equal(done.accepted,false);assert.equal(c.state.snapshot.filters.status,'open');});
test('local search operates only on the displayed snapshot',()=>{const c=seeded([a(1,'open','','needle'),a(2,'open','','hay')]);c.setSearch('needle');assert.deepEqual(filterDisplayedAlerts(c.state.snapshot.items,c.state.search,x=>x.message).map(x=>x.id),[1]);assert.equal(alertsPresentation(c.state).appliedFilters.status,'open');});
test('regeneration success records counters without inventing rows',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');const done=c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:2,resolved_count:3,open_count:4});assert.equal(done.announcement,'polite');assert.equal(c.state.lastGeneration.open_count,4);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);});
test('regeneration failure or uncertainty preserves snapshot and uses truthful copy',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');const done=c.finishMutationFailure(m.requestId,m.routeGeneration);assert.equal(done.message,ALERT_MUTATION_UNCERTAIN_MESSAGE);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);});
test('regeneration success plus refresh success replaces list once',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:0,updated_count:0,resolved_count:0,open_count:1});const r=c.startRead('regeneration-refresh',f);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2)]);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);assert.equal(c.state.feedback.mutationError,'');});
test('regeneration success plus refresh failure remains success plus warning with assertive announcement text',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:0,resolved_count:0,open_count:1});const r=c.startRead('regeneration-refresh',f);const refresh=c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[1]);assert.match(c.state.feedback.message,/Алерты обновлены/);assert.match(c.state.feedback.refreshWarning,/Не удалось обновить список/);assert.equal(c.state.feedback.mutationError,'');assert.equal(refresh.announcement,'assertive');assert.match(ALERT_REGENERATION_REFRESH_WARNING_ANNOUNCEMENT,/список не удалось перечитать/);});
test('resolve under open removes the alert from the visible snapshot',()=>{const c=seeded([a(1),a(2)]);const m=c.startMutation('resolve',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(1,'resolved'));assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('dismiss under open removes the alert from the visible snapshot',()=>{const c=seeded([a(1),a(2)]);const m=c.startMutation('dismiss',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'dismiss',a(1,'dismissed'));assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('resolve under all keeps the authoritative returned alert',()=>{const c=seeded([a(1)],{status:'all',type:'',search:''});const m=c.startMutation('resolve',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(1,'resolved'));assert.equal(c.state.snapshot.items[0].status,'resolved');});
test('dismiss under all keeps the authoritative returned alert',()=>{const c=seeded([a(1)],{status:'all',type:'',search:''});const m=c.startMutation('dismiss',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'dismiss',a(1,'dismissed'));assert.equal(c.state.snapshot.items[0].status,'dismissed');});
test('type-filter behavior is respected by authoritative mutation responses',()=>{const c=seeded([a(1,'open','low_ingredient_stock')],{status:'resolved',type:'ingredient_expired',search:''});const m=c.startMutation('resolve',c.state.routeGeneration,1);c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(1,'resolved','low_ingredient_stock'));assert.equal(c.state.snapshot.items.length,0);assert.equal(c.state.snapshot.filters.type,'ingredient_expired');});
test('duplicate mutation is rejected while a mutation owns the route',()=>{const c=seeded([a(1)]);const m=c.startMutation('resolve',c.state.routeGeneration,1);assert.equal(m.accepted,true);assert.equal(c.startMutation('dismiss',c.state.routeGeneration,1).accepted,false);assert.equal(alertsPresentation(c.state).controlsDisabled,true);});
test('stale mutation response cannot clear a newer owner',()=>{const c=seeded([a(1),a(2)]);const stale=c.startMutation('resolve',c.state.routeGeneration,1);c.state.mutation=null;const newer=c.startMutation('dismiss',c.state.routeGeneration,2);const done=c.applyMutationResponse(stale.requestId,stale.routeGeneration,1,'resolve',a(1,'resolved'));assert.equal(done.accepted,false);assert.equal(c.state.mutation.id,newer.requestId);});
test('wrong-alert DTO clears current owner, preserves snapshot and asks to refresh',()=>{const c=seeded([a(1),a(2)]);const m=c.startMutation('resolve',c.state.routeGeneration,1);const done=c.applyMutationResponse(m.requestId,m.routeGeneration,1,'resolve',a(2,'resolved'));assert.equal(done.accepted,true);assert.equal(done.announcement,'assertive');assert.equal(c.state.mutation,null);assert.deepEqual(c.state.snapshot.items.map(x=>x.status),['open','open']);assert.equal(c.state.feedback.mutationError,ALERT_INVALID_RESPONSE_MESSAGE);});
test('route leave suppresses presentation while allowing current data to commit silently',()=>{const c=new AlertsFeedbackLifecycle();const g=c.enterRoute();const r=c.startRead('initial',f,g);c.leaveRoute();const done=c.finishReadSuccess(r.requestId,g,r.filters,[a(1)]);assert.equal(done.present,false);assert.equal(c.state.snapshot.items.length,1);});
test('route leave and return creates a new generation and old callback cannot present',()=>{const c=new AlertsFeedbackLifecycle();const g1=c.enterRoute();const r=c.startRead('initial',f,g1);c.leaveRoute();const g2=c.enterRoute();const done=c.finishReadSuccess(r.requestId,g1,r.filters,[a(1)]);assert.notEqual(g1,g2);assert.equal(done.present,false);});
test('navigation adapter enters and leaves Alerts exactly on route boundary changes',()=>{const calls=[];const l={enterRoute(){calls.push('enter');return calls.length;},leaveRoute(){calls.push('leave');return calls.length;}};assert.equal(transitionAlertsRouteOwnership(l,'Главная','Алерты'),'entered');assert.equal(transitionAlertsRouteOwnership(l,'Алерты','Алерты'),'unchanged');assert.equal(transitionAlertsRouteOwnership(l,'Алерты','Заказы'),'left');assert.deepEqual(calls,['enter','leave']);});
test('busy presentation disables server controls but keeps local search explicit',()=>{const c=seeded([a(1)]);const r=c.startRead('refresh',f);let v=alertsPresentation(c.state);assert.equal(v.controlsDisabled,true);assert.equal(v.workspaceBusy,true);assert.equal(v.searchEnabled,true);c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);const m=c.startMutation('resolve',c.state.routeGeneration,1);v=alertsPresentation(c.state);assert.equal(v.resolveCopy,'Отмечаем…');assert.equal(v.controlsDisabled,true);});
test('final focus after resolve falls back to list/main when open card disappears',()=>{assert.equal(selectAlertFocusTarget(true,'alert-1-resolve',1,[{key:'alert-1-resolve',kind:'previous',enabled:true,attached:false},{key:'alert-1-heading',kind:'alert-heading',enabled:true,attached:false},{key:'alerts-list-region',kind:'list-region',enabled:true,attached:true},{key:'alerts-main-heading',kind:'main-heading',enabled:true,attached:true}]),'alerts-list-region');});
test('final focus after dismiss under all can return to affected heading',()=>{assert.equal(selectAlertFocusTarget(true,'alert-1-dismiss',1,[{key:'alert-1-dismiss',kind:'previous',enabled:true,attached:false},{key:'alert-1-heading',kind:'alert-heading',enabled:true,attached:true}]),'alert-1-heading');});
test('focus selection skips disabled previous controls and supports main-heading fallback',()=>{assert.equal(selectAlertFocusTarget(true,'prev',1,[{key:'prev',kind:'previous',enabled:false,attached:true},{key:'live',kind:'live-region',enabled:true,attached:true},{key:'alerts-main-heading',kind:'main-heading',enabled:true,attached:true}]),'alerts-main-heading');assert.equal(selectAlertFocusTarget(false,null,1,[{key:'alerts-main-heading',kind:'main-heading',enabled:true,attached:true}]),null);});

test('leave and return during initial load clears old owner and allows fresh load',()=>{const c=new AlertsFeedbackLifecycle();const g1=c.enterRoute();const old=c.startRead('initial',f,g1);c.leaveRoute();const g2=c.enterRoute();assert.equal(c.state.read,null);assert.equal(c.consumeReentryReconcile(),true);const fresh=c.startRead('initial',f,g2);assert.equal(fresh.accepted,true);assert.equal(c.finishReadSuccess(old.requestId,g1,old.filters,[a(1)]).accepted,false);c.finishReadSuccess(fresh.requestId,fresh.routeGeneration,fresh.filters,[a(2)]);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('leave and return during manual refresh clears busy state and reconciles with one fresh GET',()=>{const c=seeded([a(1)]);const old=c.startRead('refresh',f);c.leaveRoute();const g2=c.enterRoute();let getCount=0;if(c.consumeReentryReconcile()){getCount++;const fresh=c.startRead('refresh',f,g2);assert.equal(fresh.accepted,true);c.finishReadSuccess(fresh.requestId,fresh.routeGeneration,fresh.filters,[a(3)]);}assert.equal(getCount,1);assert.equal(c.finishReadFailure(old.requestId,old.routeGeneration,old.filters).accepted,false);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[3]);});
test('leave and return during resolve does not retry mutation and permits reconciliation GET',()=>{const c=seeded([a(1)]);const old=c.startMutation('resolve',c.state.routeGeneration,1);c.leaveRoute();const g2=c.enterRoute();let mutationRetries=0;let getCount=0;assert.equal(c.consumeReentryReconcile(),false);const stale=c.applyMutationResponse(old.requestId,old.routeGeneration,1,'resolve',a(1,'resolved'));assert.equal(stale.accepted,false);c.markDetachedMutationSettled();if(c.consumeReentryReconcile()){getCount++;const fresh=c.startRead('refresh',f,g2);c.finishReadSuccess(fresh.requestId,fresh.routeGeneration,fresh.filters,[a(1,'resolved')]);}assert.equal(mutationRetries,0);assert.equal(getCount,1);assert.equal(c.state.snapshot.items[0].status,'resolved');assert.equal(alertsPresentation(c.state).controlsDisabled,false);});
test('leave and return during dismiss does not retry mutation and leaves busy state',()=>{const c=seeded([a(1)]);const old=c.startMutation('dismiss',c.state.routeGeneration,1);c.leaveRoute();const g2=c.enterRoute();assert.equal(c.consumeReentryReconcile(),false);c.markDetachedMutationSettled();assert.equal(c.consumeReentryReconcile(),true);const fresh=c.startRead('refresh',f,g2);c.finishReadSuccess(fresh.requestId,fresh.routeGeneration,fresh.filters,[]);assert.equal(c.applyMutationResponse(old.requestId,old.routeGeneration,1,'dismiss',a(1,'dismissed')).accepted,false);assert.equal(c.state.snapshot.items.length,0);assert.equal(alertsPresentation(c.state).workspaceBusy,false);});
test('leave and return during regeneration POST reconciles by GET without a second mutation',()=>{const c=seeded([a(1)]);const old=c.startMutation('regenerate',c.state.routeGeneration);c.leaveRoute();const g2=c.enterRoute();let mutationRetries=0;let getCount=0;assert.equal(c.consumeReentryReconcile(),false);const stale=c.finishRegenerationSuccess(old.requestId,old.routeGeneration,{created_count:1,updated_count:0,resolved_count:0,open_count:1});assert.equal(stale.accepted,false);c.markDetachedMutationSettled();if(c.consumeReentryReconcile()){getCount++;const fresh=c.startRead('refresh',f,g2);c.finishReadSuccess(fresh.requestId,fresh.routeGeneration,fresh.filters,[a(2)]);}assert.equal(mutationRetries,0);assert.equal(getCount,1);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('old operation success or failure after return cannot present and new visit leaves busy state',()=>{const c=seeded([a(1)]);const old=c.startRead('refresh',f);c.leaveRoute();const g2=c.enterRoute();const fresh=c.startRead('refresh',f,g2);c.finishReadSuccess(fresh.requestId,fresh.routeGeneration,fresh.filters,[a(2)]);assert.equal(c.finishReadSuccess(old.requestId,old.routeGeneration,old.filters,[a(3)]).accepted,false);assert.equal(c.finishReadFailure(old.requestId,old.routeGeneration,old.filters).accepted,false);assert.equal(alertsPresentation(c.state).controlsDisabled,false);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('leaving during regeneration follow-up success suppresses final presentation but records regeneration',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');const mutation=c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:0,resolved_count:0,open_count:1});const r=c.startRead('regeneration-refresh',f);c.leaveRoute();const refresh=c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2)]);assert.equal(mutation.present,true);assert.equal(refresh.present,false);assert.equal(c.state.lastGeneration.created_count,1);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[2]);});
test('leaving during regeneration follow-up failure suppresses late warning presentation',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:0,resolved_count:0,open_count:1});const r=c.startRead('regeneration-refresh',f);c.leaveRoute();const refresh=c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(refresh.present,false);assert.equal(refresh.announcement,'none');assert.equal(c.state.lastGeneration.created_count,1);});
test('leave and return during regeneration follow-up requires current-visit reconciliation',()=>{const c=seeded([a(1)]);const m=c.startMutation('regenerate');c.finishRegenerationSuccess(m.requestId,m.routeGeneration,{created_count:1,updated_count:0,resolved_count:0,open_count:1});const oldRefresh=c.startRead('regeneration-refresh',f);c.leaveRoute();const g2=c.enterRoute();assert.equal(c.consumeReentryReconcile(),true);const fresh=c.startRead('refresh',f,g2);c.finishReadSuccess(fresh.requestId,fresh.routeGeneration,fresh.filters,[a(3)]);assert.equal(c.finishReadSuccess(oldRefresh.requestId,oldRefresh.routeGeneration,oldRefresh.filters,[a(2)]).accepted,false);assert.deepEqual(c.state.snapshot.items.map(x=>x.id),[3]);});
test('busy presentation applies disabled reset state to empty snapshots',()=>{const c=seeded([],{status:'resolved',type:'',search:''});const r=c.startRead('refresh',c.displayedFilters());const view=alertsPresentation(c.state);assert.equal(view.controlsDisabled,true);assert.equal(c.state.snapshot.items.length,0);assert.equal(r.accepted,true);});

test('all-control binding wires two reload controls once each',()=>{let calls=0;const buttons=[{n:0,addEventListener(t,fn){this.fn=fn;this.n++;}},{n:0,addEventListener(t,fn){this.fn=fn;this.n++;}}];assert.equal(bindAlertsActionControls({querySelectorAll:()=>buttons},'[data-action="reload-alerts"]',()=>calls++),2);buttons.forEach(b=>{assert.equal(b.n,1);b.fn();});assert.equal(calls,2);});
test('zero-control binding is safe',()=>{assert.equal(bindAlertsActionControls({querySelectorAll:()=>[]},'[data-action="reload-alerts"]',()=>{}),0);});

test('mutation settles while away before return creates next-entry reconciliation without retry',()=>{const c=seeded([a(1)]);const old=c.startMutation('resolve',c.state.routeGeneration,1);c.leaveRoute();const result=c.applyMutationResponse(old.requestId,old.routeGeneration,1,'resolve',a(1,'resolved'));assert.equal(result.present,false);let gets=0, retries=0;const g=c.enterRoute();assert.equal(c.consumeReentryReconcile(),true);if(true){gets++;const r=c.startRead('refresh',f,g);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(1,'resolved')]);}assert.equal(gets,1);assert.equal(retries,0);assert.equal(c.state.snapshot.items[0].status,'resolved');});
test('mutation failure while away creates durable next-entry reconciliation',()=>{const c=seeded([a(1)]);const old=c.startMutation('dismiss',c.state.routeGeneration,1);c.leaveRoute();const result=c.finishMutationFailure(old.requestId,old.routeGeneration);assert.equal(result.present,false);const g=c.enterRoute();assert.equal(c.consumeReentryReconcile(),true);const r=c.startRead('refresh',f,g);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(1)]);assert.equal(c.state.snapshot.items[0].status,'open');});
test('invalid DTO while away creates durable next-entry reconciliation without updating another alert',()=>{const c=seeded([a(1),a(2)]);const old=c.startMutation('resolve',c.state.routeGeneration,1);c.leaveRoute();const result=c.applyMutationResponse(old.requestId,old.routeGeneration,1,'resolve',a(2,'resolved'));assert.equal(result.present,false);assert.deepEqual(c.state.snapshot.items.map(x=>x.status),['open','open']);const g=c.enterRoute();assert.equal(c.consumeReentryReconcile(),true);const r=c.startRead('refresh',f,g);c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(1),a(2)]);assert.deepEqual(c.state.snapshot.items.map(x=>x.status),['open','open']);});
test('read success while away is ignored for presentation and read failure while away requires next reconciliation',()=>{let c=seeded([a(1)]);let r=c.startRead('refresh',f);c.leaveRoute();let done=c.finishReadSuccess(r.requestId,r.routeGeneration,r.filters,[a(2)]);assert.equal(done.present,false);c=seeded([a(1)]);r=c.startRead('refresh',f);c.leaveRoute();done=c.finishReadFailure(r.requestId,r.routeGeneration,r.filters);assert.equal(done.present,false);assert.equal(c.consumeReentryReconcile(),true);});
test('repeated entries consume reconciliation exactly once and stale callbacks cannot clear current GET',()=>{const c=seeded([a(1)]);const old=c.startMutation('resolve',c.state.routeGeneration,1);c.leaveRoute();c.enterRoute();assert.equal(c.consumeReentryReconcile(),false);c.leaveRoute();c.enterRoute();assert.equal(c.consumeReentryReconcile(),false);c.markDetachedMutationSettled();assert.equal(c.consumeReentryReconcile(),true);assert.equal(c.consumeReentryReconcile(),false);const current=c.startRead('refresh',f);assert.equal(c.finishReadSuccess(old.requestId,old.routeGeneration,f,[a(9)]).accepted,false);assert.equal(c.state.read.id,current.requestId);});
