import test from 'node:test';
import assert from 'node:assert/strict';
import { bindActionControls, DashboardOnboardingFeedbackLifecycle, onboardingFailureMessage, onboardingSuccessMessage, selectOnboardingFocusTarget } from '../dist-tests/dashboard-onboarding-feedback/dashboard-onboarding-feedback.js';
const data=(n)=>({orders:Array(n).fill({}),clients:[],alerts:[],purchaseSuggestions:[],productionBatches:[]});
const emptyData=()=>data(0);
const state=(step='welcome')=>({has_started:true,is_completed:false,current_step:step,completed_steps:[],available_steps:['welcome','stock']});
function assertDashboardInvariant(c){ const d=c.state.dashboard; assert.equal(Boolean(d.message&&d.error),false); assert.equal(Boolean(d.message&&d.warning),false); assert.equal(d.status==='loading'&&Boolean(d.message||d.error||d.warning),false); assert.equal(Boolean(d.error&&d.warning),false); }
function assertOnboardingInvariant(c){ const o=c.state.onboarding; assert.equal(Boolean(o.message&&o.error),false); assert.equal(Boolean(o.message&&o.warning),false); assert.equal((o.loadActive||o.mutationActive)&&Boolean(o.message||o.error||o.warning),false); assert.equal(o.status==='unavailable'&&Boolean(o.state),false); }

test('dashboard initial success/failure and manual refresh announcements',()=>{ const c=new DashboardOnboardingFeedbackLifecycle(); let r=c.startDashboardLoad('initial'); let f=c.finishDashboardSuccess(r.requestId,data(1)); assert.equal(f.announcement,'none'); assert.equal(c.state.dashboard.hasLoadedSnapshot,true); assertDashboardInvariant(c); r=c.startDashboardLoad('refresh'); f=c.finishDashboardSuccess(r.requestId,data(2)); assert.equal(f.announcement,'polite'); assert.equal(c.state.dashboard.message.includes('Обзор обновлён'),true); assertDashboardInvariant(c); const fresh=new DashboardOnboardingFeedbackLifecycle(); r=fresh.startDashboardLoad('initial'); f=fresh.finishDashboardFailure(r.requestId,true); assert.equal(f.announcement,'assertive'); assert.equal(fresh.state.dashboard.error.includes('Не удалось загрузить'),true); assertDashboardInvariant(fresh); });

test('dashboard refresh failure preserves non-empty and valid empty snapshots',()=>{ for (const snapshot of [data(3), emptyData()]) { const c=new DashboardOnboardingFeedbackLifecycle(); let r=c.startDashboardLoad('initial'); c.finishDashboardSuccess(r.requestId,snapshot); assert.equal(c.state.dashboard.hasLoadedSnapshot,true); r=c.startDashboardLoad('refresh'); const f=c.finishDashboardFailure(r.requestId,true); assert.equal(f.announcement,'assertive'); assert.equal(c.state.dashboard.data.orders.length,snapshot.orders.length); assert.equal(c.state.dashboard.error,''); assert.match(c.state.dashboard.warning,/последние|ранее|устар/); assertDashboardInvariant(c); } });

test('dashboard duplicate refresh and stale callbacks cannot mutate newer request',()=>{ const c=new DashboardOnboardingFeedbackLifecycle(); let a=c.startDashboardLoad('initial'); c.finishDashboardSuccess(a.requestId,data(1)); a=c.startDashboardLoad('refresh'); assert.equal(c.startDashboardLoad('refresh').accepted,false); const oldId=a.requestId; c.finishDashboardSuccess(oldId,data(2)); const b=c.startDashboardLoad('refresh'); assert.equal(c.finishDashboardSuccess(oldId,data(9)).accepted,false); assert.equal(c.finishDashboardFailure(oldId,true).accepted,false); assert.equal(c.state.dashboard.active,true); assert.equal(c.state.dashboard.data.orders.length,2); assert.equal(c.state.dashboard.message,''); assert.equal(c.state.dashboard.warning,''); assert.equal(c.state.dashboard.error,''); c.finishDashboardSuccess(b.requestId,data(4)); assert.equal(c.state.dashboard.data.orders.length,4); assertDashboardInvariant(c); });

test('dashboard new operation clears feedback and lost ownership suppresses transient feedback',()=>{ const c=new DashboardOnboardingFeedbackLifecycle(); let r=c.startDashboardLoad('initial'); c.finishDashboardSuccess(r.requestId,data(1)); r=c.startDashboardLoad('refresh'); c.finishDashboardFailure(r.requestId,true); assert.ok(c.state.dashboard.warning); r=c.startDashboardLoad('refresh'); assert.equal(c.state.dashboard.warning,''); assert.equal(c.state.dashboard.error,''); assert.equal(c.state.dashboard.message,''); let f=c.finishDashboardSuccess(r.requestId,data(5),false); assert.equal(f.announcement,'none'); assert.equal(c.state.dashboard.message,''); r=c.startDashboardLoad('refresh'); f=c.finishDashboardFailure(r.requestId,false); assert.equal(f.announcement,'none'); assert.equal(c.state.dashboard.warning,''); assert.equal(c.state.dashboard.status,'ready'); assertDashboardInvariant(c); });

test('onboarding initial and manual load lifecycle clears stale feedback and preserves stale state',()=>{ const c=new DashboardOnboardingFeedbackLifecycle(); let r=c.startOnboardingLoad('initial'); let f=c.finishOnboardingLoadSuccess(r.requestId,state('welcome'),true); assert.equal(f.announcement,'none'); assert.equal(c.state.onboarding.status,'ready'); r=c.startOnboardingMutation('start'); c.finishOnboardingMutationFailure(r.requestId,onboardingFailureMessage('start'),true); assert.ok(c.state.onboarding.error); r=c.startOnboardingLoad('refresh'); assert.equal(c.state.onboarding.error,''); assert.equal(c.state.onboarding.message,''); assert.equal(c.state.onboarding.warning,''); f=c.finishOnboardingLoadSuccess(r.requestId,state('stock'),true); assert.equal(f.announcement,'polite'); assert.equal(c.state.onboarding.message,'Список первых шагов обновлён.'); assertOnboardingInvariant(c); r=c.startOnboardingLoad('refresh'); f=c.finishOnboardingLoadFailure(r.requestId,true); assert.equal(f.announcement,'assertive'); assert.equal(c.state.onboarding.status,'ready'); assert.equal(c.state.onboarding.state.current_step,'stock'); assert.match(c.state.onboarding.warning,/последнее успешно/); assertOnboardingInvariant(c); });

test('onboarding initial load failure unavailable only without state and lost ownership suppresses feedback',()=>{ const c=new DashboardOnboardingFeedbackLifecycle(); let r=c.startOnboardingLoad('initial'); let f=c.finishOnboardingLoadFailure(r.requestId,true); assert.equal(f.announcement,'assertive'); assert.equal(c.state.onboarding.status,'unavailable'); assert.equal(c.state.onboarding.state,null); const c2=new DashboardOnboardingFeedbackLifecycle(); r=c2.startOnboardingLoad('initial'); f=c2.finishOnboardingLoadSuccess(r.requestId,state(),false); assert.equal(f.announcement,'none'); assert.equal(c2.state.onboarding.message,''); r=c2.startOnboardingLoad('refresh'); f=c2.finishOnboardingLoadFailure(r.requestId,false); assert.equal(f.announcement,'none'); assert.equal(c2.state.onboarding.status,'ready'); assert.equal(c2.state.onboarding.warning,''); assertOnboardingInvariant(c2); });

test('onboarding duplicate refresh and mutation/refresh conflicts',()=>{ const c=new DashboardOnboardingFeedbackLifecycle(); c.finishOnboardingLoadSuccess(c.startOnboardingLoad('initial').requestId,state()); let r=c.startOnboardingLoad('refresh'); assert.equal(r.accepted,true); assert.equal(c.startOnboardingLoad('refresh').accepted,false); assert.equal(c.startOnboardingMutation('skip').accepted,false); c.finishOnboardingLoadSuccess(r.requestId,state('stock'),true); r=c.startOnboardingMutation('skip'); assert.equal(r.accepted,true); assert.equal(c.startOnboardingLoad('refresh').accepted,false); assert.equal(c.startOnboardingMutation('reset').accepted,false); c.finishOnboardingMutationSuccess(r.requestId,state('stock'),onboardingSuccessMessage('skip'),true); assertOnboardingInvariant(c); });

test('onboarding stale refresh success/failure cannot clear current owner',()=>{ const c=new DashboardOnboardingFeedbackLifecycle(); let r=c.startOnboardingLoad('initial'); c.finishOnboardingLoadSuccess(r.requestId,state('welcome'),true); r=c.startOnboardingLoad('refresh'); c.finishOnboardingLoadSuccess(r.requestId,state('stock'),true); const oldId=r.requestId; const next=c.startOnboardingLoad('refresh'); assert.equal(c.finishOnboardingLoadSuccess(oldId,state('welcome'),true).accepted,false); assert.equal(c.finishOnboardingLoadFailure(oldId,true).accepted,false); assert.equal(c.state.onboarding.loadActive,true); assert.equal(c.state.onboarding.state.current_step,'stock'); c.finishOnboardingLoadSuccess(next.requestId,state('stock'),true); assertOnboardingInvariant(c); });

for (const action of ['start','complete-step','skip','reset']) test(`onboarding ${action} success and failure use authoritative response`,()=>{ const c=new DashboardOnboardingFeedbackLifecycle(); const before=state('welcome'); c.finishOnboardingLoadSuccess(c.startOnboardingLoad('initial').requestId,before); let r=c.startOnboardingMutation(action); let updated=state('stock'); let f=c.finishOnboardingMutationSuccess(r.requestId,updated,onboardingSuccessMessage(action),true); assert.equal(f.announcement,'polite'); assert.equal(c.state.onboarding.state,updated); assert.equal(c.state.onboarding.error,''); r=c.startOnboardingMutation(action); f=c.finishOnboardingMutationFailure(r.requestId,onboardingFailureMessage(action),true); assert.equal(f.announcement,'assertive'); assert.equal(c.state.onboarding.state,updated); assert.equal(c.state.onboarding.message,''); assert.equal(c.state.onboarding.error,onboardingFailureMessage(action)); assertOnboardingInvariant(c); });

test('onboarding stale mutation success and failure cannot overwrite current busy owner',()=>{ const c=new DashboardOnboardingFeedbackLifecycle(); c.finishOnboardingLoadSuccess(c.startOnboardingLoad('initial').requestId,state('welcome')); let a=c.startOnboardingMutation('start'); c.invalidateOnboardingMutation(); let b=c.startOnboardingMutation('skip'); assert.equal(c.finishOnboardingMutationSuccess(a.requestId,state('old'),onboardingSuccessMessage('start'),true).accepted,false); assert.equal(c.finishOnboardingMutationFailure(a.requestId,onboardingFailureMessage('start'),true).accepted,false); assert.equal(c.state.onboarding.mutationActive,true); assert.equal(c.state.onboarding.action,'skip'); assert.equal(c.state.onboarding.state.current_step,'welcome'); assert.equal(c.state.onboarding.message,''); c.finishOnboardingMutationSuccess(b.requestId,state('stock'),onboardingSuccessMessage('skip'),true); assert.equal(c.state.onboarding.state.current_step,'stock'); assertOnboardingInvariant(c); });

test('onboarding lost ownership suppresses announcements and focus',()=>{ const c=new DashboardOnboardingFeedbackLifecycle(); c.finishOnboardingLoadSuccess(c.startOnboardingLoad('initial').requestId,state()); let r=c.startOnboardingMutation('reset'); let f=c.finishOnboardingMutationSuccess(r.requestId,state('stock'),onboardingSuccessMessage('reset'),false); assert.equal(f.announcement,'none'); assert.equal(f.focusAllowed,false); assert.equal(c.state.onboarding.message,''); r=c.startOnboardingMutation('reset'); f=c.finishOnboardingMutationFailure(r.requestId,onboardingFailureMessage('reset'),false); assert.equal(f.announcement,'none'); assert.equal(f.focusAllowed,false); assert.equal(c.state.onboarding.error,''); assertOnboardingInvariant(c); });

test('focus policy chooses real targets without live regions',()=>{ const previous={key:'complete-step',kind:'previous',enabled:true,attached:true}; const disabled={...previous,enabled:false}; const detached={...previous,attached:false}; const heading={key:'onboarding-heading',kind:'heading',enabled:true,attached:true}; const primary={key:'start-onboarding',kind:'primary',enabled:true,attached:true}; const live={key:'announcer',kind:'live-region',enabled:true,attached:true}; assert.equal(selectOnboardingFocusTarget(true,'complete-step',[previous,heading,primary]),'complete-step'); assert.equal(selectOnboardingFocusTarget(true,'complete-step',[disabled,heading,primary]),'onboarding-heading'); assert.equal(selectOnboardingFocusTarget(true,'complete-step',[detached,primary]),'start-onboarding'); assert.equal(selectOnboardingFocusTarget(true,'missing',[heading,primary,live]),'onboarding-heading'); assert.equal(selectOnboardingFocusTarget(true,'missing',[primary,live]),'start-onboarding'); assert.equal(selectOnboardingFocusTarget(false,'complete-step',[previous,heading,primary]),null); assert.equal(selectOnboardingFocusTarget(true,'announcer',[live]),null); });


test('bindActionControls wires every Dashboard reload control exactly once and handles zero matches',()=>{ let calls=0; const controls=[fakeControl(),fakeControl()]; const root={querySelectorAll:(selector)=>selector==='[data-action="reload-dashboard"]'?controls:[]}; assert.equal(bindActionControls(root,'[data-action="reload-dashboard"]',()=>{ calls+=1; }),2); assert.equal(controls[0].listenerCount(),1); assert.equal(controls[1].listenerCount(),1); controls[0].click(); assert.equal(calls,1); controls[1].click(); assert.equal(calls,2); assert.equal(bindActionControls({querySelectorAll:()=>[]},'[data-action="reload-dashboard"]',()=>{ calls+=1; }),0); assert.equal(calls,2); });

test('bindActionControls wires multiple onboarding refresh controls and lifecycle still rejects duplicate refresh',()=>{ let calls=0; const controls=[fakeControl(),fakeControl(),fakeControl()]; const root={querySelectorAll:(selector)=>selector==='[data-action="refresh-onboarding"]'?controls:[]}; assert.equal(bindActionControls(root,'[data-action="refresh-onboarding"]',()=>{ calls+=1; }),3); controls[0].click(); controls[1].click(); controls[2].click(); assert.equal(calls,3); const lifecycle=new DashboardOnboardingFeedbackLifecycle(); lifecycle.finishOnboardingLoadSuccess(lifecycle.startOnboardingLoad('initial').requestId,state()); const first=lifecycle.startOnboardingLoad('refresh'); const duplicate=lifecycle.startOnboardingLoad('refresh'); assert.equal(first.accepted,true); assert.equal(duplicate.accepted,false); });

function fakeControl(){ const listeners=[]; return { addEventListener(type, listener){ assert.equal(type,'click'); listeners.push(listener); }, click(){ listeners.forEach((listener)=>listener()); }, listenerCount(){ return listeners.length; } }; }
