import test from 'node:test';
import assert from 'node:assert/strict';
import { createLocalArtifactRouteRuntime } from '../dist-tests/local-artifacts-reports-feedback/local-artifacts-reports-runtime.js';
import { transitionLocalArtifactsReportsRouteOwnership } from '../dist-tests/local-artifacts-reports-feedback/local-artifacts-reports-route.js';
import { bindEveryActionControl } from '../dist-tests/local-artifacts-reports-feedback/local-artifacts-reports-feedback.js';
import { localArtifactPresentation } from '../dist-tests/local-artifacts-reports-feedback/local-artifact-presentation.js';

const messages = { loading:'loading', refreshing:'refreshing', reconciling:'reconciling', initialError:'initial error', refreshError:'refresh warning', refreshSuccess:'refresh ok', mutationBusy:'busy', mutationSuccess:'created', mutationError:'create failed', mutationAmbiguous:'Нельзя подтвердить результат: файл мог быть создан. Обновите список перед повтором.', invalidMutationResponse:'invalid created', mutationRefreshWarning:'created but refresh failed', reconciliationFailed:'still cannot confirm' };
function deferred(){let resolve,reject;const promise=new Promise((res,rej)=>{resolve=res;reject=rej});return {promise,resolve,reject};}
const artifact=(id=1)=>({id,filename:`file-${id}.json`,path:`/tmp/file-${id}.json`,created_at:'2026-07-23T00:00:00Z',size_bytes:10,reason:'manual'});
function makeRoute(route='backups'){
  const h={active:true,renders:0,polite:[],assertive:[],focus:[],reads:[],mutations:[],applied:[],created:[],postCount:0,readCount:0};
  const runtime=createLocalArtifactRouteRuntime({ route, mutationKind: route==='exports'?'create-export':route==='reportDocuments'?'create-report-document':'create-backup', messages, read:()=>{h.readCount++;const d=deferred();h.reads.push(d);return d.promise;}, mutate:()=>{h.postCount++;const d=deferred();h.mutations.push(d);return d.promise;}, validateCreated:(x)=>Boolean(x?.filename&&x?.path || x?.id&&x?.filename), ownsRoute:()=>h.active, applyRead:(s)=>h.applied.push(s), applyCreated:(c)=>h.created.push(c), render:()=>{if(h.active)h.renders++}, announce:(m,k)=>h[k==='assertive'?'assertive':'polite'].push(m), focus:(k)=>h.focus.push(k) });
  return {h,runtime};
}
const flush=()=>new Promise(r=>setImmediate(r));

test('production runtime: detached settles before return reconciles with GET and no POST repeat',async()=>{const {h,runtime}=makeRoute('backups');runtime.enter();runtime.create({reason:'manual'});assert.equal(h.postCount,1);runtime.leave();h.active=false;h.mutations[0].resolve({created:artifact(1),message:'created'});await flush();assert.deepEqual(h.polite,[]);assert.deepEqual(h.focus,[]);assert.equal(h.renders,1);h.active=true;runtime.enter();runtime.reconcile();assert.equal(h.readCount,1);h.reads[0].resolve({items:[artifact(1)]});await flush();assert.equal(h.postCount,1);assert.equal(runtime.lifecycle.state.reconciliationRequired,false);});

test('production runtime: return before detached settlement keeps detached immutable and queues authoritative reconciliation',async()=>{const {h,runtime}=makeRoute('exports');runtime.enter();runtime.create({reason:'manual'});runtime.leave();h.active=false;h.active=true;runtime.enter();runtime.reconcile();assert.equal(h.readCount,1);h.mutations[0].resolve({created:artifact(2),message:'old success'});await flush();assert.deepEqual(h.polite,[]);assert.deepEqual(h.focus,[]);assert.equal(runtime.lifecycle.state.reconciliationRequired,true);h.reads[0].resolve({items:[artifact(2)]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);assert.equal(h.postCount,1);});

test('production runtime: detached failure creates no feedback but requires read reconciliation',async()=>{const {h,runtime}=makeRoute('reportDocuments');runtime.enter();runtime.create({format:'pdf'});runtime.leave();h.active=false;h.mutations[0].reject(new Error('definite'));await flush();assert.deepEqual(h.assertive,[]);assert.equal(runtime.lifecycle.state.reconciliationRequired,true);h.active=true;runtime.enter();runtime.reconcile();assert.equal(h.readCount,1);});

for (const route of ['backups','exports','reportDocuments']) test(`ambiguous ${route} locks mutation until accepted GET reconciliation`,async()=>{const {h,runtime}=makeRoute(route);runtime.enter();runtime.create({});h.mutations[0].reject(new TypeError('Failed to fetch'));await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.equal(runtime.presentation().canCreate,false);runtime.create({});assert.equal(h.postCount,1);runtime.reconcile();h.reads[0].reject(new Error('GET failed'));await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,true);runtime.reconcile();h.reads[1].resolve({items:[]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);runtime.create({});assert.equal(h.postCount,2);});

test('stale GET cannot clear reconciliation lock or newer owner',async()=>{const {h,runtime}=makeRoute('backups');runtime.enter();runtime.create({});h.mutations[0].reject(new TypeError('network'));await flush();const stale=runtime.reconcile();runtime.leave();runtime.enter();h.reads[0].resolve({items:[]});await flush();assert.equal(stale.accepted,true);assert.equal(runtime.lifecycle.state.reconciliationRequired,true);});

for (const route of ['backups','exports','reportDocuments']) test(`success plus refresh warning on ${route} keeps success and warning presentation`,async()=>{const {h,runtime}=makeRoute(route);runtime.enter();runtime.load('initial');h.reads[0].resolve({items:[artifact(0)]});await flush();runtime.create({});h.mutations[0].resolve({created:artifact(3),message:'created ok'});await flush();assert.equal(h.postCount,1);assert.equal(h.created.length,1);assert.equal(h.polite.at(-1),'created ok');h.reads[1].reject(new Error('read fail'));await flush();const p=runtime.presentation();assert.equal(p.feedback.success,'created ok');assert.equal(p.feedback.warning,'created but refresh failed');assert.equal(p.feedback.error,'');assert.equal(h.polite.at(-1),'created but refresh failed');});

test('definite mutation failure is error/assertive and focuses create target',async()=>{const {h,runtime}=makeRoute('backups');runtime.enter();runtime.create({});h.mutations[0].reject({status:500});await flush();const p=runtime.presentation();assert.equal(p.feedback.error,'create failed');assert.deepEqual(h.assertive,['create failed']);assert.deepEqual(h.focus,['b3-backups-create']);});

test('initial failure focuses retry, initial success is silent, manual Reports refresh is polite and read-only',async()=>{const {h,runtime}=makeRoute('reports');runtime.enter();runtime.load('initial');h.reads[0].reject(new Error('down'));await flush();assert.deepEqual(h.assertive,['initial error']);assert.deepEqual(h.focus,['b3-reports-retry']);runtime.load('initial');h.reads[1].resolve({overview:{},inventory:{},orders:{},production:{},finance:{}});await flush();assert.equal(h.polite.length,0);runtime.load('refresh');h.reads[2].resolve({overview:{fresh:true},inventory:{},orders:{},production:{},finance:{}});await flush();assert.deepEqual(h.polite,['refresh ok']);assert.equal(h.postCount,0);assert.equal(h.readCount,3);});

test('stale and absent route completions do not announce/focus/render',async()=>{const {h,runtime}=makeRoute('exports');runtime.enter();runtime.load('initial');runtime.leave();h.active=false;h.reads[0].resolve({items:[artifact(1)]});await flush();assert.deepEqual(h.polite,[]);assert.deepEqual(h.focus,[]);assert.equal(h.applied.length,0);});

test('route adapter same-route transition does not re-enter and leaving invalidates reads',()=>{const a=makeRoute('backups').runtime,b=makeRoute('exports').runtime;transitionLocalArtifactsReportsRouteOwnership({backups:a,exports:b},null,'backups');assert.equal(a.lifecycle.state.routeGeneration,1);transitionLocalArtifactsReportsRouteOwnership({backups:a,exports:b},'backups','backups');assert.equal(a.lifecycle.state.routeGeneration,1);const r=a.load('initial');transitionLocalArtifactsReportsRouteOwnership({backups:a,exports:b},'backups','exports');assert.equal(a.lifecycle.finishReadSuccess(r,{items:[]}).accepted,false);assert.equal(b.lifecycle.state.routeGeneration,1);});

test('all rendered retry/reload controls bind through production helper',()=>{const calls=[];const controls=[{addEventListener:(t,cb)=>calls.push([t,cb])},{addEventListener:(t,cb)=>calls.push([t,cb])}];const count=bindEveryActionControl({querySelectorAll:(s)=>s==='[data-action="reload-backups"]'?controls:[]},'[data-action="reload-backups"]',()=>{});assert.equal(count,2);assert.equal(calls.length,2);});

test('main wiring source uses production runtime factory and route adapter, not only helper lifecycle',async()=>{const fs=await import('node:fs/promises');const source=await fs.readFile(new URL('../src/main.ts', import.meta.url),'utf8');assert.match(source,/createLocalArtifactRouteRuntime<BackupReadSnapshot/);assert.match(source,/transitionLocalArtifactsReportsRouteOwnership\(\{ backups: backupRuntime/);assert.doesNotMatch(source,/mutation\.detached = false/);assert.doesNotMatch(source,/feedback\.error \|\| .*feedback\.warning/);});

test('local artifact presentation remains unchanged for open/download metadata',()=>{const p=localArtifactPresentation({filename:null,path:'/safe/export.json',folderKind:'exports'});assert.equal(p.filename,'export.json');assert.match(p.folderLabel,/экспорта/i);});
