import test from 'node:test';
import assert from 'node:assert/strict';
import { createLocalArtifactRouteRuntime } from '../dist-tests/local-artifacts-reports-feedback/local-artifacts-reports-runtime.js';
import { transitionLocalArtifactsReportsRouteOwnership } from '../dist-tests/local-artifacts-reports-feedback/local-artifacts-reports-route.js';
import { bindLocalArtifactsReportsControls } from '../dist-tests/local-artifacts-reports-feedback/local-artifacts-reports-bindings.js';
import { localArtifactPresentation } from '../dist-tests/local-artifacts-reports-feedback/local-artifact-presentation.js';

const messages = { loading:'loading', refreshing:'refreshing', reconciling:'reconciling', initialError:'initial error', refreshError:'refresh warning', refreshSuccess:'refresh ok', mutationBusy:'busy', mutationSuccess:'created', mutationError:'create failed', mutationAmbiguous:'Нельзя подтвердить результат: файл мог быть создан. Обновите список перед повтором.', invalidMutationResponse:'invalid created', mutationRefreshWarning:'created but refresh failed', reconciliationFailed:'still cannot confirm' };
function deferred(){let resolve,reject;const promise=new Promise((res,rej)=>{resolve=res;reject=rej});return {promise,resolve,reject};}
const artifact=(id=1)=>({id,filename:`file-${id}.json`,path:`/tmp/file-${id}.json`,created_at:'2026-07-23T00:00:00Z',size_bytes:10,reason:'manual'});
function makeRoute(route='backups'){
  const h={active:true,renders:0,polite:[],assertive:[],focus:[],reads:[],mutations:[],applied:[],created:[],postCount:0,readCount:0};
  const deps={ route, messages, read:()=>{h.readCount++;const d=deferred();h.reads.push(d);return d.promise;}, validateCreated:(x)=>Boolean(x?.filename&&x?.path || x?.id&&x?.filename), ownsRoute:()=>h.active, applyRead:(s)=>h.applied.push(s), applyCreated:(c)=>h.created.push(c), render:()=>{if(h.active)h.renders++}, announce:(m,k)=>h[k==='assertive'?'assertive':'polite'].push(m), focus:(k)=>h.focus.push(k) };
  if(route!=='reports'){deps.mutationKind=route==='exports'?'create-export':route==='reportDocuments'?'create-report-document':'create-backup';deps.mutate=()=>{h.postCount++;const d=deferred();h.mutations.push(d);return d.promise;};}
  const runtime=createLocalArtifactRouteRuntime(deps);
  return {h,runtime};
}
const flush=()=>new Promise(r=>setImmediate(r));

class Control{constructor(attrs){this.attrs=attrs;this.dataset={};this.listeners=[];this.value=attrs.value||'';for(const [k,v] of Object.entries(attrs)){if(k.startsWith('data-')) this.dataset[k.slice(5).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=v;}}addEventListener(type,cb){this.listeners.push({type,cb});}}
class StrictRoot{constructor(controls){this.controls=controls;} assertValid(selector){if(/\[data-[^\]]+"\s+data-[^\]]+\]/.test(selector)) throw new SyntaxError(`Invalid selector ${selector}`);} matches(c,selector){this.assertValid(selector);const parts=[...selector.matchAll(/\[([^=\]]+)="([^"]+)"\]/g)].map(([,k,v])=>[k,v]);return parts.length>0&&parts.every(([k,v])=>c.attrs[k]===v);}querySelectorAll(selector){return this.controls.filter(c=>this.matches(c,selector));}querySelector(selector){return this.querySelectorAll(selector)[0]??null;}}
const controls=()=>[new Control({'data-action':'reload-backups'}),new Control({'data-action':'reload-backups'}),new Control({'data-form':'backup-create'}),new Control({'data-action':'create-backup'}),new Control({'data-action':'reload-exports'}),new Control({'data-action':'reload-exports'}),new Control({'data-form':'export-create'}),new Control({'data-action':'create-export'}),new Control({'data-action':'reload-report-documents'}),new Control({'data-action':'reload-report-documents'}),new Control({'data-form':'report-document-create'}),new Control({'data-action':'report-document-reason',value:'note'}),new Control({'data-action':'navigate-report-documents-related','data-section':'Отчеты'}),new Control({'data-action':'reload-reports'}),new Control({'data-action':'select-report-tab','data-report':'finance'}),new Control({'data-action':'navigate-report-related','data-section':'Документы отчетов'}),new Control({'data-action':'unrelated'})];
const callbacks=()=>({reloadBackups(){},submitBackup(){},reloadExports(){},submitExport(){},reloadReportDocuments(){},submitReportDocument(){},updateReportDocumentReason(){},navigateReportDocumentsRelated(){},reloadReports(){},selectReportTab(){},navigateReportRelated(){}});

 test('production binding selectors are valid, complete, non-duplicating and reject old malformed compounds',()=>{const root=new StrictRoot(controls());assert.throws(()=>root.querySelectorAll('[data-action="reload-backups" data-focus-key="b3-backups-refresh"]'),SyntaxError);const counts=bindLocalArtifactsReportsControls(root,callbacks());assert.equal(counts.backupReload,2);assert.equal(counts.exportReload,2);assert.equal(counts.reportDocumentsReload,2);assert.equal(counts.backupForm,1);assert.equal(counts.exportForm,1);assert.equal(counts.reportDocumentsForm,1);assert.equal(counts.reportsReload,1);assert.equal(root.controls.find(c=>c.attrs['data-action']==='unrelated').listeners.length,0);for(const c of root.controls) assert.equal(new Set(c.listeners.map(l=>l.type)).size,c.listeners.length);});

test('production runtime: detached settles before return reconciles with GET and no POST repeat',async()=>{const {h,runtime}=makeRoute('backups');runtime.enter();runtime.create({reason:'manual'});assert.equal(h.postCount,1);runtime.leave();h.active=false;h.mutations[0].resolve({created:artifact(1),message:'created'});await flush();assert.deepEqual(h.polite,[]);assert.deepEqual(h.focus,[]);assert.equal(h.renders,1);h.active=true;runtime.enter();runtime.reconcile();assert.equal(h.readCount,1);h.reads[0].resolve({items:[artifact(1)]});await flush();assert.equal(h.postCount,1);assert.equal(runtime.lifecycle.state.reconciliationRequired,false);});

test('return before detached settlement queues post-settlement reconciliation and provisional GET cannot clear lock',async()=>{const {h,runtime}=makeRoute('exports');runtime.enter();runtime.create({reason:'manual'});runtime.leave();h.active=false;h.active=true;runtime.enter();runtime.reconcile();assert.equal(h.readCount,1);h.mutations[0].resolve({created:artifact(2),message:'old success'});await flush();assert.deepEqual(h.polite,[]);assert.deepEqual(h.focus,[]);assert.equal(runtime.lifecycle.state.reconciliationRequired,true);h.reads[0].resolve({items:[]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.equal(h.readCount,2);h.reads[1].resolve({items:[artifact(2)]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);assert.equal(h.postCount,1);});

test('detached reconciliation failed GETs keep lock and never render detached completion',async()=>{const {h,runtime}=makeRoute('reportDocuments');runtime.enter();runtime.create({format:'pdf'});runtime.leave();h.active=false;h.mutations[0].reject(new Error('definite'));await flush();assert.deepEqual(h.assertive,[]);assert.deepEqual(h.focus,[]);assert.equal(runtime.lifecycle.state.reconciliationRequired,true);h.active=true;runtime.enter();runtime.reconcile();h.reads[0].reject(new Error('GET failed'));await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.equal(h.postCount,1);});

for (const route of ['backups','exports','reportDocuments']) test(`ambiguous ${route} locks mutation until accepted GET reconciliation`,async()=>{const {h,runtime}=makeRoute(route);runtime.enter();runtime.create({});h.mutations[0].reject(new TypeError('Failed to fetch'));await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.equal(runtime.presentation().canCreate,false);runtime.create({});assert.equal(h.postCount,1);runtime.reconcile();h.reads[0].reject(new Error('GET failed'));await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,true);runtime.reconcile();h.reads[1].resolve({items:[]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);runtime.create({});assert.equal(h.postCount,2);});

test('stale GET cannot clear reconciliation lock or newer owner',async()=>{const {h,runtime}=makeRoute('backups');runtime.enter();runtime.create({});h.mutations[0].reject(new TypeError('network'));await flush();const stale=runtime.reconcile();runtime.leave();runtime.enter();h.reads[0].resolve({items:[]});await flush();assert.equal(stale.accepted,true);assert.equal(runtime.lifecycle.state.reconciliationRequired,true);});

for (const route of ['backups','exports','reportDocuments']) test(`success plus refresh warning on ${route} keeps success and warning presentation`,async()=>{const {h,runtime}=makeRoute(route);runtime.enter();runtime.load('initial');h.reads[0].resolve({items:[artifact(0)]});await flush();runtime.create({});h.mutations[0].resolve({created:artifact(3),message:'created ok'});await flush();assert.equal(h.postCount,1);assert.equal(h.created.length,1);assert.equal(h.polite.at(-1),'created ok');h.reads[1].reject(new Error('read fail'));await flush();const p=runtime.presentation();assert.equal(p.feedback.success,'created ok');assert.equal(p.feedback.warning,'created but refresh failed');assert.equal(p.feedback.error,'');assert.equal(h.polite.at(-1),'created but refresh failed');});

test('definite and invalid mutation failures are operation-owned and focus correct targets',async()=>{const {h,runtime}=makeRoute('backups');runtime.enter();runtime.create({});h.mutations[0].reject({status:500});await flush();assert.equal(runtime.presentation().feedback.error,'create failed');assert.deepEqual(h.assertive,['create failed']);assert.deepEqual(h.focus,['b3-backups-create']);const other=makeRoute('backups');other.runtime.enter();other.runtime.create({});other.h.mutations[0].resolve({created:{filename:'',path:''},message:'bad'});await flush();assert.equal(other.runtime.lifecycle.state.reconciliationRequired,true);assert.equal(other.runtime.presentation().feedback.success,'');assert.equal(other.runtime.presentation().feedback.error,'invalid created');assert.equal(other.h.focus.at(-1),'b3-backups-refresh');});

test('same message announcements are request-owned and rerender does not duplicate one completion',async()=>{const {h,runtime}=makeRoute('reports');runtime.enter();runtime.load('initial');h.reads[0].resolve({});await flush();runtime.load('refresh');h.reads[1].resolve({});await flush();runtime.load('refresh');h.reads[2].resolve({});await flush();assert.deepEqual(h.polite,['refresh ok','refresh ok']);assert.equal(h.postCount,0);});

test('feedback ownership clears old success but retains last-created metadata separately',async()=>{const {h,runtime}=makeRoute('exports');runtime.enter();runtime.create({});h.mutations[0].resolve({created:artifact(1),message:'created ok'});await flush();assert.equal(runtime.presentation().feedback.success,'created ok');runtime.load('mutation-refresh');h.reads[0].resolve({items:[artifact(1)]});await flush();runtime.create({});assert.equal(runtime.presentation().feedback.success,'');h.mutations[1].reject(new TypeError('network'));await flush();assert.equal(runtime.presentation().feedback.warning,messages.mutationAmbiguous);assert.equal(runtime.presentation().feedback.success,'');assert.deepEqual(runtime.lifecycle.state.lastCreated,artifact(1));});

test('Reports runtime is genuinely read-only',async()=>{const {h,runtime}=makeRoute('reports');runtime.enter();const create=runtime.create();assert.equal(create.reason,'no-mutation');runtime.load('initial');h.reads[0].resolve({overview:{},inventory:{},orders:{},production:{},finance:{}});await flush();runtime.load('refresh');h.reads[1].resolve({overview:{fresh:true},inventory:{},orders:{},production:{},finance:{}});await flush();assert.equal(h.readCount,2);assert.equal(h.postCount,0);assert.equal(h.mutations.length,0);});

test('navigation clears eligible B3.3 transient feedback and preserves reconciliation obligation',()=>{for(const route of ['backups','exports','reportDocuments','reports']){const {runtime}=makeRoute(route);runtime.enter();runtime.lifecycle.state.feedback.success='done';transitionLocalArtifactsReportsRouteOwnership({[route]:runtime},route,null);runtime.lifecycle.clearTransientFeedback();assert.equal(runtime.presentation().feedback.success,'');}const {runtime}=makeRoute('backups');runtime.enter();runtime.create({});runtime.lifecycle.finishMutationFailure({accepted:true,requestId:1,routeGeneration:1,reason:'',kind:'create-backup'},true);runtime.lifecycle.clearTransientFeedback();assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.equal(runtime.presentation().feedback.warning,messages.mutationAmbiguous);});

test('focus targets and duplicate focus attributes are valid markup contracts',async()=>{const fs=await import('node:fs/promises');const source=await fs.readFile(new URL('../src/main.ts', import.meta.url),'utf8');for(const key of ['b3-backups-retry','b3-backups-refresh','b3-backups-create','b3-backups-last-created','b3-backups-content','b3-exports-retry','b3-exports-refresh','b3-exports-create','b3-exports-last-created','b3-exports-content','b3-report-documents-retry','b3-report-documents-refresh','b3-report-documents-create','b3-report-documents-last-created','b3-report-documents-content','b3-reports-retry','b3-reports-refresh','b3-reports-content']) assert.match(source,new RegExp(`data-focus-key="${key}"`));for (const key of ['b3-backups-create','b3-exports-create','b3-report-documents-create']) assert.match(source,new RegExp(`<form[^>]*data-focus-key="${key}"[^>]*tabindex="-1"|<form[^>]*tabindex="-1"[^>]*data-focus-key="${key}"`));for (const key of ['b3-backups-retry','b3-exports-retry','b3-report-documents-retry','b3-reports-retry']) assert.match(source,new RegExp(`<button[^>]*data-focus-key="${key}"`));for (const key of ['b3-backups-content','b3-exports-content','b3-report-documents-content','b3-reports-content','b3-backups-last-created','b3-exports-last-created','b3-report-documents-last-created']) assert.match(source,new RegExp(`tabindex="-1"[^>]*data-focus-key="${key}"|data-focus-key="${key}"[^>]*tabindex="-1"`));assert.match(source,/const disabled = backupUiState\.actionStatus === 'creating' \|\| backupUiState\.status === 'loading' \|\| backupLifecycle\.state\.reconciliationRequired/);assert.match(source,/data-form="backup-create"/);assert.match(source,/const disabled = exportUiState\.actionStatus === 'creating' \|\| exportUiState\.status === 'loading' \|\| exportLifecycle\.state\.reconciliationRequired/);assert.match(source,/data-form="export-create"/);assert.match(source,/const disabled = reportDocumentsUiState\.actionStatus === 'creating' \|\| reportDocumentsUiState\.status === 'loading' \|\| reportDocumentsLifecycle\.state\.reconciliationRequired/);assert.match(source,/data-form="report-document-create"/);for (const tag of source.match(/<[^>]*data-focus-key=[^>]*>/g) ?? []) assert.doesNotMatch(tag,/data-focus-key="([^"]+)"[^>]*data-focus-key=/);});

test('main wiring delegates B3.3 controls to production binding module',async()=>{const fs=await import('node:fs/promises');const source=await fs.readFile(new URL('../src/main.ts', import.meta.url),'utf8');assert.match(source,/bindLocalArtifactsReportsControls\(root/);assert.doesNotMatch(source,/\[data-[^\]]+"\s+data-[^\]]+\]/);assert.doesNotMatch(source,/mutation\.detached = false/);assert.doesNotMatch(source,/lastAnnouncement\s*=/);});


test('provisional reconciliation GET success before detached settlement cannot clear lock until post-settlement GET',async()=>{const {h,runtime}=makeRoute('backups');runtime.enter();runtime.create({});runtime.leave();h.active=false;h.active=true;runtime.enter();runtime.reconcile();assert.equal(h.readCount,1);h.reads[0].resolve({items:['provisional']});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.equal(runtime.presentation().canCreate,false);assert.equal(h.readCount,1);h.mutations[0].resolve({created:artifact(10),message:'detached created'});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.equal(h.readCount,2);assert.deepEqual(h.polite,[]);assert.deepEqual(h.focus,[]);h.reads[1].resolve({items:[artifact(10)]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);assert.equal(h.postCount,1);});

test('provisional reconciliation GET failure after detached settlement starts exactly one authoritative GET',async()=>{const {h,runtime}=makeRoute('exports');runtime.enter();runtime.create({});runtime.leave();h.active=false;h.active=true;runtime.enter();runtime.reconcile();assert.equal(h.readCount,1);h.mutations[0].resolve({created:artifact(11),message:'detached created'});await flush();assert.equal(h.readCount,1);h.reads[0].reject(new Error('provisional failed'));await flush();await flush();assert.equal(h.readCount,2);assert.equal(runtime.lifecycle.state.reconciliationRequired,true);h.reads[1].resolve({items:[artifact(11)]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);assert.equal(h.postCount,1);});

test('authoritative second reconciliation GET failure does not loop and manual retry can clear',async()=>{const {h,runtime}=makeRoute('reportDocuments');runtime.enter();runtime.create({});runtime.leave();h.active=false;h.active=true;runtime.enter();runtime.reconcile();h.mutations[0].resolve({created:artifact(12),message:'detached created'});await flush();h.reads[0].reject(new Error('first failed'));await flush();await flush();assert.equal(h.readCount,2);h.reads[1].reject(new Error('second failed'));await flush();assert.equal(h.readCount,2);assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.equal(runtime.presentation().canCreate,false);runtime.reconcile();assert.equal(h.readCount,3);h.reads[2].resolve({items:[artifact(12)]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);assert.equal(h.postCount,1);});

test('queued reconciliation survives route leave and stale queued completion cannot clear lock',async()=>{const {h,runtime}=makeRoute('backups');runtime.enter();runtime.create({});runtime.leave();h.active=false;h.active=true;runtime.enter();runtime.reconcile();h.mutations[0].resolve({created:artifact(13),message:'detached created'});await flush();h.reads[0].reject(new Error('first failed'));await flush();await flush();assert.equal(h.readCount,2);runtime.leave();h.active=false;h.reads[1].resolve({items:[artifact(13)]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.deepEqual(h.focus,['b3-backups-retry']);h.active=true;runtime.enter();runtime.reconcile();h.reads[2].resolve({items:[artifact(13)]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);});

test('export accepted-only entity counts ignore invalid and detached responses',async()=>{let counts={previous:1};const h={active:true,renders:0,polite:[],assertive:[],focus:[],reads:[],mutations:[],postCount:0};const deps={route:'exports',mutationKind:'create-export',messages,read:()=>{const d=deferred();h.reads.push(d);return d.promise;},mutate:()=>{h.postCount++;const d=deferred();h.mutations.push(d);return d.promise;},validateCreated:(x)=>Boolean(x?.filename&&x?.path),ownsRoute:()=>h.active,applyRead(){},applyCreated(){},render(){h.renders++},announce:(m,k)=>h[k==='assertive'?'assertive':'polite'].push(m),focus:(k)=>h.focus.push(k)};const runtime=createLocalArtifactRouteRuntime(deps);runtime.enter();runtime.create({});h.mutations[0].resolve({created:{filename:'',path:''},message:'bad',commitAccepted:()=>{counts={bad:99}}});await flush();assert.deepEqual(counts,{previous:1});runtime.reconcile();h.reads[0].resolve({items:[]});await flush();runtime.create({});h.mutations[1].resolve({created:artifact(20),message:'ok',commitAccepted:()=>{counts={accepted:2}}});await flush();assert.deepEqual(counts,{accepted:2});runtime.load('mutation-refresh');h.reads[1].resolve({items:[artifact(20)]});await flush();runtime.create({});runtime.leave();h.active=false;h.mutations[2].resolve({created:artifact(21),message:'detached',commitAccepted:()=>{counts={detached:3}}});await flush();assert.deepEqual(counts,{accepted:2});});

test('report document reason clears only after accepted success',async()=>{let reason='weekly check';const h={active:true,renders:0,polite:[],assertive:[],focus:[],reads:[],mutations:[]};const deps={route:'reportDocuments',mutationKind:'create-report-document',messages,read:()=>{const d=deferred();h.reads.push(d);return d.promise;},mutate:()=>{const d=deferred();h.mutations.push(d);return d.promise;},validateCreated:(x)=>Boolean(x?.id&&x?.filename&&x?.format),ownsRoute:()=>h.active,applyRead(){},applyCreated(){},render(){h.renders++},announce:(m,k)=>h[k==='assertive'?'assertive':'polite'].push(m),focus:(k)=>h.focus.push(k)};const runtime=createLocalArtifactRouteRuntime(deps);runtime.enter();runtime.create({});h.mutations[0].resolve({created:{id:null,filename:'',format:''},message:'bad',commitAccepted:()=>{reason=''}});await flush();assert.equal(reason,'weekly check');runtime.reconcile();h.reads[0].resolve({items:[]});await flush();runtime.create({});h.mutations[1].reject(new TypeError('network'));await flush();assert.equal(reason,'weekly check');runtime.reconcile();h.reads[1].resolve({items:[]});await flush();runtime.create({});h.mutations[2].reject({status:500});await flush();assert.equal(reason,'weekly check');runtime.create({});h.mutations[3].resolve({created:{id:1,filename:'doc.md',format:'markdown'},message:'ok',commitAccepted:()=>{reason=''}});await flush();assert.equal(reason,'');});

test('initial and manual refresh announcements plus stale and absent route behavior',async()=>{const {h,runtime}=makeRoute('reports');runtime.enter();runtime.load('initial');h.reads[0].reject(new Error('down'));await flush();assert.deepEqual(h.assertive,['initial error']);assert.deepEqual(h.focus,['b3-reports-retry']);runtime.load('initial');h.reads[1].resolve({overview:{}});await flush();assert.deepEqual(h.polite,[]);runtime.load('refresh');h.reads[2].resolve({overview:{fresh:true}});await flush();assert.deepEqual(h.polite,['refresh ok']);const stale=runtime.load('refresh');runtime.leave();h.active=false;h.reads[3].resolve({overview:{stale:true}});await flush();assert.equal(stale.accepted,true);assert.deepEqual(h.polite,['refresh ok']);assert.deepEqual(h.focus,['b3-reports-retry','b3-reports-content']);});

test('route adapter same-route transition skips duplicate enter and route return preserves reconciliation',()=>{const {runtime}=makeRoute('backups');transitionLocalArtifactsReportsRouteOwnership({backups:runtime},null,'backups');const gen=runtime.lifecycle.state.routeGeneration;transitionLocalArtifactsReportsRouteOwnership({backups:runtime},'backups','backups');assert.equal(runtime.lifecycle.state.routeGeneration,gen);runtime.lifecycle.finishMutationFailure({accepted:true,requestId:0,routeGeneration:gen,reason:'',kind:'create-backup'},true);runtime.lifecycle.state.reconciliationRequired=true;transitionLocalArtifactsReportsRouteOwnership({backups:runtime,exports:makeRoute('exports').runtime},'backups','exports');assert.equal(runtime.lifecycle.state.reconciliationRequired,true);});


async function seedSnapshot(runtime,h){runtime.enter();runtime.load('initial');assert.equal(h.readCount,1);h.reads[0].resolve({items:[artifact(0)]});await flush();assert.ok(runtime.lifecycle.state.snapshot);}

test('snapshot-aware provisional failure before detached settlement does not auto-retry until settlement',async()=>{const {h,runtime}=makeRoute('backups');await seedSnapshot(runtime,h);runtime.create({});assert.equal(h.postCount,1);runtime.leave();h.active=false;h.active=true;runtime.enter();runtime.reconcile();assert.equal(h.readCount,2);h.reads[1].reject(new Error('provisional failed before settlement'));await flush();await flush();assert.ok(runtime.lifecycle.state.snapshot);assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.equal(runtime.presentation().canCreate,false);assert.equal(h.readCount,2);h.mutations[0].resolve({created:artifact(30),message:'detached'});await flush();assert.equal(h.readCount,3);h.reads[2].resolve({items:[artifact(30)]});await flush();await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);assert.equal(h.readCount,3);assert.equal(h.postCount,1);});

test('snapshot-aware provisional failure after detached settlement starts one authoritative GET',async()=>{const {h,runtime}=makeRoute('exports');await seedSnapshot(runtime,h);runtime.create({});runtime.leave();h.active=false;h.active=true;runtime.enter();runtime.reconcile();assert.equal(h.readCount,2);h.mutations[0].resolve({created:artifact(31),message:'detached'});await flush();h.reads[1].reject(new Error('provisional failed after settlement'));await flush();await flush();assert.equal(h.readCount,3);assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.equal(h.postCount,1);h.reads[2].resolve({items:[artifact(31)]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);assert.equal(h.readCount,3);});

test('snapshot-aware authoritative failure consumes queue and does not loop before manual retry',async()=>{const {h,runtime}=makeRoute('reportDocuments');await seedSnapshot(runtime,h);runtime.create({});runtime.leave();h.active=false;h.active=true;runtime.enter();runtime.reconcile();h.mutations[0].resolve({created:artifact(32),message:'detached'});await flush();h.reads[1].reject(new Error('provisional failed'));await flush();await flush();assert.equal(h.readCount,3);h.reads[2].reject(new Error('authoritative failed'));await flush();await flush();await flush();assert.equal(h.readCount,3);assert.equal(runtime.lifecycle.state.pendingReconciliationAfterRead,false);assert.equal(runtime.lifecycle.state.reconciliationRequired,true);assert.equal(runtime.presentation().canCreate,false);assert.equal(runtime.presentation().feedback.warning,'still cannot confirm');assert.equal(h.postCount,1);runtime.reconcile();assert.equal(h.readCount,4);h.reads[3].resolve({items:[artifact(32)]});await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);});

test('snapshot-aware authoritative success clears lock without extra GET',async()=>{const {h,runtime}=makeRoute('backups');await seedSnapshot(runtime,h);runtime.create({});runtime.leave();h.active=false;h.active=true;runtime.enter();runtime.reconcile();h.mutations[0].resolve({created:artifact(33),message:'detached'});await flush();h.reads[1].reject(new Error('provisional failed'));await flush();await flush();assert.equal(h.readCount,3);h.reads[2].resolve({items:[artifact(33)]});await flush();await flush();assert.equal(runtime.lifecycle.state.reconciliationRequired,false);assert.equal(runtime.lifecycle.state.pendingReconciliationAfterRead,false);assert.equal(h.readCount,3);assert.equal(h.postCount,1);});

test('validated known success is the only path to applyCreated and commitAccepted',async()=>{const calls=[];const h={active:true,renders:0,polite:[],assertive:[],focus:[],reads:[],mutations:[],postCount:0};const deps={route:'exports',mutationKind:'create-export',messages,read:()=>{const d=deferred();h.reads.push(d);return d.promise;},mutate:()=>{h.postCount++;const d=deferred();h.mutations.push(d);return d.promise;},validateCreated:(x)=>Boolean(x?.filename&&x?.path),ownsRoute:()=>h.active,applyRead(){},applyCreated:(c)=>calls.push(['apply',c.filename]),render(){h.renders++},announce:(m,k)=>h[k==='assertive'?'assertive':'polite'].push(m),focus:(k)=>h.focus.push(k)};const runtime=createLocalArtifactRouteRuntime(deps);runtime.enter();runtime.create({});h.mutations[0].resolve({created:{filename:'',path:''},message:'bad',commitAccepted:()=>calls.push(['commit','bad'])});await flush();assert.deepEqual(calls,[]);assert.equal(runtime.lifecycle.state.lastCreated,null);runtime.reconcile();h.reads[0].resolve({items:[]});await flush();runtime.create({});runtime.leave();h.active=false;h.mutations[1].resolve({created:artifact(34),message:'detached',commitAccepted:()=>calls.push(['commit','detached'])});await flush();assert.deepEqual(calls,[]);h.active=true;runtime.enter();runtime.reconcile();h.reads[1].resolve({items:[]});await flush();runtime.create({});const old=h.mutations[2];runtime.leave();runtime.enter();old.resolve({created:artifact(35),message:'stale',commitAccepted:()=>calls.push(['commit','stale'])});await flush();assert.deepEqual(calls,[]);runtime.reconcile();h.reads[2].resolve({items:[]});await flush();runtime.create({});h.mutations[3].resolve({created:artifact(36),message:'ok',commitAccepted:()=>calls.push(['commit','ok'])});await flush();assert.deepEqual(calls,[['commit','ok'],['apply','file-36.json']]);assert.equal(runtime.lifecycle.state.lastCreated.filename,'file-36.json');});

test('local artifact presentation remains unchanged for open/download metadata',()=>{const p=localArtifactPresentation({filename:null,path:'/safe/export.json',folderKind:'exports'});assert.equal(p.filename,'export.json');assert.match(p.folderLabel,/экспорта/i);});
