import test from 'node:test';
import assert from 'node:assert/strict';
import { PurchaseSuggestionsFeedbackLifecycle, DEFAULT_PURCHASE_FILTERS, PURCHASE_MARKED_MESSAGE } from '../dist-tests/purchase-suggestions-feedback/purchase-suggestions-feedback.js';
import { createPurchaseSuggestionsRuntime } from '../dist-tests/purchase-suggestions-feedback/purchase-suggestions-runtime.js';
import { transitionPurchaseSuggestionsRouteOwnership } from '../dist-tests/purchase-suggestions-feedback/purchase-suggestions-route.js';
import { createInitialPurchaseReferenceState, createPurchaseSuggestionsReferenceDataController } from '../dist-tests/purchase-suggestions-feedback/purchase-suggestions-reference-data.js';
import { bindPurchaseSuggestionControls } from '../dist-tests/purchase-suggestions-feedback/purchase-suggestions-bindings.js';

const tick = () => new Promise(r => setImmediate(r));
function deferred(){let resolve,reject; const promise=new Promise((res,rej)=>{resolve=res; reject=rej}); return {promise,resolve,reject};}
const row=(id, extra={})=>({id,item_type:'ingredient',item_id:10,item_name_snapshot:`Item ${id}`,recommended_quantity:'1',unit:'g',reason:'manual',status:'open',created_at:'2026-01-01',updated_at:'2026-01-01',...extra});
function harness(){const lifecycle=new PurchaseSuggestionsFeedbackLifecycle(); let owns=true; const calls={read:[],regen:0,create:[],update:[],mark:[],dismiss:[],announce:[],focus:[],render:0}; const q={read:[],regen:[],create:[],update:[],mark:[],dismiss:[]}; const rt=createPurchaseSuggestionsRuntime(lifecycle,{read:f=>{calls.read.push(f); const d=deferred(); q.read.push(d); return d.promise;},regenerate:()=>{calls.regen++; const d=deferred(); q.regen.push(d); return d.promise;},create:p=>{calls.create.push(p); const d=deferred(); q.create.push(d); return d.promise;},update:(id,p)=>{calls.update.push([id,p]); const d=deferred(); q.update.push(d); return d.promise;},markPurchased:id=>{calls.mark.push(id); const d=deferred(); q.mark.push(d); return d.promise;},dismiss:id=>{calls.dismiss.push(id); const d=deferred(); q.dismiss.push(d); return d.promise;},ownsRoute:()=>owns,render:()=>{calls.render++},announce:(m,k)=>calls.announce.push([k,m]),focus:k=>calls.focus.push(k),onValidCreate:()=>{calls.createClosed=true},onValidUpdate:()=>{calls.updateClosed=true}}); return {lifecycle,rt,calls,q,setOwns:v=>{owns=v}};}
function fakeRoot(map){return {querySelectorAll(sel){return map[sel]??[]}}} function ctl(dataset={},disabled=false){return {dataset,disabled,events:{},addEventListener(type,fn){this.events[type]=fn},click(){this.events.click?.({currentTarget:this})},change(){this.events.change?.({currentTarget:this})},value:dataset.value??''}}

test('route transition enters when non-Purchases becomes Purchases',()=>{let enter=0,leave=0; assert.equal(transitionPurchaseSuggestionsRouteOwnership({previousSection:'Главная',nextSection:'Закупки',runtime:{enter:()=>enter++,leave:()=>leave++}}),'enter'); assert.deepEqual([enter,leave],[1,0]);});
test('route transition leaves when Purchases becomes non-Purchases',()=>{let enter=0,leave=0; assert.equal(transitionPurchaseSuggestionsRouteOwnership({previousSection:'Закупки',nextSection:'Главная',runtime:{enter:()=>enter++,leave:()=>leave++}}),'leave'); assert.deepEqual([enter,leave],[0,1]);});
test('route transition ignores Purchases to Purchases navigation',()=>{let enter=0,leave=0; assert.equal(transitionPurchaseSuggestionsRouteOwnership({previousSection:'Закупки',nextSection:'Закупки',runtime:{enter:()=>enter++,leave:()=>leave++}}),'none'); assert.deepEqual([enter,leave],[0,0]);});
test('route transition ignores non-Purchases to non-Purchases navigation',()=>{let enter=0,leave=0; transitionPurchaseSuggestionsRouteOwnership({previousSection:'Главная',nextSection:'Помощь',runtime:{enter:()=>enter++,leave:()=>leave++}}); assert.deepEqual([enter,leave],[0,0]);});
test('initial direct Purchases route enters once',()=>{let enter=0; transitionPurchaseSuggestionsRouteOwnership({previousSection:null,nextSection:'Закупки',runtime:{enter:()=>enter++,leave:()=>{}}}); assert.equal(enter,1);});
test('initial non-Purchases route does not enter',()=>{let enter=0; transitionPurchaseSuggestionsRouteOwnership({previousSection:null,nextSection:'Главная',runtime:{enter:()=>enter++,leave:()=>{}}}); assert.equal(enter,0);});
test('sidebar navigation uses route transition contract',()=>{let enter=0; transitionPurchaseSuggestionsRouteOwnership({previousSection:'Главная',nextSection:'Закупки',runtime:{enter:()=>enter++,leave:()=>{}}}); assert.equal(enter,1);});
test('browser Back leaving Purchases calls leave',()=>{let leave=0; transitionPurchaseSuggestionsRouteOwnership({previousSection:'Закупки',nextSection:'Главная',runtime:{enter:()=>{},leave:()=>leave++}}); assert.equal(leave,1);});
test('browser Forward entering Purchases calls enter',()=>{let enter=0; transitionPurchaseSuggestionsRouteOwnership({previousSection:'Главная',nextSection:'Закупки',runtime:{enter:()=>enter++,leave:()=>{}}}); assert.equal(enter,1);});
test('repeated popstate same section creates no duplicate ownership',()=>{let enter=0; transitionPurchaseSuggestionsRouteOwnership({previousSection:'Закупки',nextSection:'Закупки',runtime:{enter:()=>enter++,leave:()=>{}}}); assert.equal(enter,0);});

test('initial runtime read succeeds with non-empty snapshot',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([row(1)]); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,1);});
test('initial runtime read succeeds with empty snapshot',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([]); await tick(); assert.deepEqual(h.lifecycle.state.snapshot.items,[]);});
test('initial runtime read failure owns assertive message',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].reject(new Error('x')); await tick(); assert.match(h.calls.announce[0][1],/Не удалось загрузить/);});
test('initial retry starts one accepted read after failure',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].reject(new Error('x')); await tick(); h.rt.read('initial',DEFAULT_PURCHASE_FILTERS); assert.equal(h.calls.read.length,2);});
test('refresh success preserves and replaces snapshot',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([row(1)]); await tick(); h.rt.read('refresh',DEFAULT_PURCHASE_FILTERS); h.q.read[1].resolve([row(2)]); await tick(); assert.equal(h.lifecycle.state.snapshot.items[0].id,2);});
test('refresh failure preserves non-empty snapshot',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([row(1)]); await tick(); h.rt.read('refresh',DEFAULT_PURCHASE_FILTERS); h.q.read[1].reject(new Error('x')); await tick(); assert.equal(h.lifecycle.state.snapshot.items[0].id,1);});
test('refresh failure preserves empty snapshot',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([]); await tick(); h.rt.read('refresh',DEFAULT_PURCHASE_FILTERS); h.q.read[1].reject(new Error('x')); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,0);});
test('status filter success commits captured filter',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([row(1)]); await tick(); const f={...DEFAULT_PURCHASE_FILTERS,status:'all'}; h.rt.read('filter',f); h.q.read[1].resolve([row(1,{status:'purchased'})]); await tick(); assert.equal(h.lifecycle.state.snapshot.filters.status,'all');});
test('status filter failure preserves old filter',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([row(1)]); await tick(); h.rt.read('filter',{...DEFAULT_PURCHASE_FILTERS,status:'all'}); h.q.read[1].reject(new Error('x')); await tick(); assert.equal(h.lifecycle.state.snapshot.filters.status,'open');});
test('reason filter failure preserves old filter',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([row(1)]); await tick(); h.rt.read('filter',{...DEFAULT_PURCHASE_FILTERS,reason:'manual'}); h.q.read[1].reject(new Error('x')); await tick(); assert.equal(h.lifecycle.state.snapshot.filters.reason,'');});
test('item-type filter failure preserves old filter',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([row(1)]); await tick(); h.rt.read('filter',{...DEFAULT_PURCHASE_FILTERS,itemType:'packaging'}); h.q.read[1].reject(new Error('x')); await tick(); assert.equal(h.lifecycle.state.snapshot.filters.itemType,'');});
test('pending filter is not committed before success',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([row(1)]); await tick(); h.rt.read('filter',{...DEFAULT_PURCHASE_FILTERS,status:'all'}); assert.equal(h.lifecycle.state.snapshot.filters.status,'open');});
test('duplicate read is rejected by lifecycle owner',()=>{const h=harness(); h.rt.enter(); const s=h.rt.read('refresh',DEFAULT_PURCHASE_FILTERS); assert.equal(s.accepted,false);});
test('stale success after leave is rejected',async()=>{const h=harness(); h.rt.enter(); h.rt.leave(); h.q.read[0].resolve([row(1)]); await tick(); assert.equal(h.lifecycle.state.snapshot,null);});
test('stale failure after leave is rejected',async()=>{const h=harness(); h.rt.enter(); h.rt.leave(); h.q.read[0].reject(new Error('x')); await tick(); assert.equal(h.calls.announce.length,0);});
test('local search filters only current snapshot',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([row(1,{item_name_snapshot:'Крем'}),row(2,{item_name_snapshot:'Тара'})]); await tick(); h.lifecycle.setSearch('крем'); const items=(await import('../dist-tests/purchase-suggestions-feedback/purchase-suggestions-feedback.js')).purchaseSuggestionsPresentation(h.lifecycle.state).items; assert.equal(items.length,1);});

test('regeneration owned success sends one POST and one GET',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.regenerate(); h.q.regen[0].resolve({created_count:1,updated_count:0,archived_count:0,open_count:1}); await tick(); assert.deepEqual([h.calls.regen,h.calls.read.length],[1,1]);});
test('regeneration POST failure starts zero GETs',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.regenerate(); h.q.regen[0].reject(new Error('x')); await tick(); assert.equal(h.calls.read.length,0);});
test('regeneration POST success and GET failure preserves success and warning',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.regenerate(); h.q.regen[0].resolve({created_count:2,updated_count:0,archived_count:0,open_count:2}); await tick(); h.q.read[0].reject(new Error('x')); await tick(); assert.match(h.lifecycle.state.feedback.success,/новых — 2/); assert.match(h.calls.announce.at(-1)[1],/Действие выполнено/);});
test('regeneration is not retried automatically',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.regenerate(); h.q.regen[0].reject(new Error('x')); await tick(); assert.equal(h.calls.regen,1);});
test('detached regeneration settlement creates no GET while away',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.regenerate(); h.setOwns(false); h.rt.leave(); h.q.regen[0].resolve({created_count:1,updated_count:0,archived_count:0,open_count:1}); await tick(); assert.equal(h.calls.read.length,0);});
test('return after detached settlement starts one reconciliation',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.regenerate(); h.setOwns(false); h.rt.leave(); h.q.regen[0].resolve({created_count:1,updated_count:0,archived_count:0,open_count:1}); await tick(); h.setOwns(true); h.rt.enter(); assert.equal(h.calls.read.length,1);});
test('return before detached settlement waits for settlement',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.regenerate(); h.setOwns(false); h.rt.leave(); h.setOwns(true); h.rt.enter(); assert.equal(h.calls.read.length,0); h.q.regen[0].resolve({created_count:1,updated_count:0,archived_count:0,open_count:1}); await tick(); assert.equal(h.calls.read.length,1);});

test('manual create sends one POST',()=>{const h=harness(); h.lifecycle.state.snapshot={items:[],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.create({item_type:'ingredient',item_id:10,recommended_quantity:'1',unit:'g'}); assert.equal(h.calls.create.length,1);});
test('manual create valid DTO applies without list GET',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.create({item_type:'ingredient',item_id:10,recommended_quantity:'1',unit:'g'}); h.q.create[0].resolve(row(9)); await tick(); assert.equal(h.lifecycle.state.snapshot.items[0].id,9); assert.equal(h.calls.read.length,0);});
test('manual create success clears completed draft through callback',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.create({item_type:'ingredient',item_id:10,recommended_quantity:'1',unit:'g'}); h.q.create[0].resolve(row(9)); await tick(); assert.equal(h.calls.createClosed,true);});
test('manual create failure preserves draft callback absence',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.create({item_type:'ingredient',item_id:10,recommended_quantity:'1',unit:'g'}); h.q.create[0].reject(new Error('x')); await tick(); assert.equal(h.calls.createClosed,undefined);});
test('manual create wrong item type is rejected',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.create({item_type:'ingredient',item_id:10,recommended_quantity:'1',unit:'g'}); h.q.create[0].resolve(row(9,{item_type:'packaging'})); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,0);});
test('manual create wrong item ID is rejected',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.create({item_type:'ingredient',item_id:10,recommended_quantity:'1',unit:'g'}); h.q.create[0].resolve(row(9,{item_id:11})); await tick(); assert.equal(h.lifecycle.state.needsReconciliation,true);});
test('manual create wrong reason is rejected',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.create({item_type:'ingredient',item_id:10,recommended_quantity:'1',unit:'g'}); h.q.create[0].resolve(row(9,{reason:'below_minimum_stock'})); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,0);});
test('detached manual success creates no announcement and one reconciliation',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.create({item_type:'ingredient',item_id:10,recommended_quantity:'1',unit:'g'}); h.setOwns(false); h.rt.leave(); h.q.create[0].resolve(row(9)); await tick(); assert.deepEqual([h.calls.announce.length,h.lifecycle.state.needsReconciliation],[0,true]);});

test('edit valid DTO updates expected row without GET',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.update(1,{recommended_quantity:'2',unit:'g'}); h.q.update[0].resolve(row(1,{recommended_quantity:'2'})); await tick(); assert.deepEqual([h.lifecycle.state.snapshot.items[0].recommended_quantity,h.calls.read.length],['2',0]);});
test('edit failure keeps close callback unused',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.update(1,{recommended_quantity:'2',unit:'g'}); h.q.update[0].reject(new Error('x')); await tick(); assert.equal(h.calls.updateClosed,undefined);});
test('edit wrong returned ID cannot update another row',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1),row(2)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.update(1,{recommended_quantity:'2',unit:'g'}); h.q.update[0].resolve(row(2,{recommended_quantity:'9'})); await tick(); assert.equal(h.lifecycle.state.snapshot.items.find(x=>x.id===2).recommended_quantity,'1');});
test('detached edit success reconciles once',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.update(1,{recommended_quantity:'2',unit:'g'}); h.setOwns(false); h.rt.leave(); h.q.update[0].resolve(row(1,{recommended_quantity:'2'})); await tick(); assert.equal(h.lifecycle.state.needsReconciliation,true);});
test('terminal row cannot begin edit by lifecycle-compatible guard',()=>{const closed=row(1,{status:'purchased'}); assert.notEqual(closed.status,'open');});

test('mark purchased open filter removes item and announces stock truth',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.markPurchased(1); h.q.mark[0].resolve(row(1,{status:'purchased'})); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,0); assert.equal(h.calls.announce[0][1],PURCHASE_MARKED_MESSAGE);});
test('mark purchased all filter retains item',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:{...DEFAULT_PURCHASE_FILTERS,status:'all'},loaded:true}; h.rt.markPurchased(1); h.q.mark[0].resolve(row(1,{status:'purchased'})); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,1);});
test('mark purchased purchased filter retains compatible item',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[],filters:{...DEFAULT_PURCHASE_FILTERS,status:'purchased'},loaded:true}; h.rt.markPurchased(1); h.q.mark[0].resolve(row(1,{status:'purchased'})); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,1);});
test('mark purchased does not call stock API or list GET',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.markPurchased(1); h.q.mark[0].resolve(row(1,{status:'purchased'})); await tick(); assert.equal(h.calls.read.length,0);});
test('mark purchased wrong ID rejected',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1),row(2)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.markPurchased(1); h.q.mark[0].resolve(row(2,{status:'purchased'})); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,2);});

test('dismiss open filter removes item',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.dismiss(1); h.q.dismiss[0].resolve(row(1,{status:'dismissed'})); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,0);});
test('dismiss all filter retains history',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:{...DEFAULT_PURCHASE_FILTERS,status:'all'},loaded:true}; h.rt.dismiss(1); h.q.dismiss[0].resolve(row(1,{status:'dismissed'})); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,1);});
test('dismiss dismissed filter retains compatible item',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[],filters:{...DEFAULT_PURCHASE_FILTERS,status:'dismissed'},loaded:true}; h.rt.dismiss(1); h.q.dismiss[0].resolve(row(1,{status:'dismissed'})); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,1);});
test('dismiss wrong ID rejected',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1),row(2)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.dismiss(1); h.q.dismiss[0].resolve(row(2,{status:'dismissed'})); await tick(); assert.equal(h.lifecycle.state.snapshot.items.length,2);});

test('FinishResult contains its own message',()=>{const l=new PurchaseSuggestionsFeedbackLifecycle(); const s=l.startRead('initial',DEFAULT_PURCHASE_FILTERS); const r=l.finishReadFailure(s.requestId,s.routeGeneration,s.filters); assert.match(r.message,/Не удалось загрузить/);});
test('runtime announces result message rather than shared success',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.lifecycle.state.feedback.success='Старый успех'; h.rt.read('refresh',DEFAULT_PURCHASE_FILTERS); h.q.read[0].reject(new Error('x')); await tick(); assert.doesNotMatch(h.calls.announce[0][1],/Старый успех/);});
test('old success is not included in later mutation failure',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.lifecycle.state.feedback.success='Старый успех'; h.rt.update(1,{}); h.q.update[0].reject(new Error('x')); await tick(); assert.doesNotMatch(h.calls.announce[0][1],/Старый успех/);});
test('old mutation error is not included in later success',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.lifecycle.state.feedback.mutationError='Старая ошибка'; h.rt.markPurchased(1); h.q.mark[0].resolve(row(1,{status:'purchased'})); await tick(); assert.doesNotMatch(h.calls.announce[0][1],/Старая ошибка/);});
test('filter failure announces only filter warning',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([row(1)]); await tick(); h.rt.read('filter',{...DEFAULT_PURCHASE_FILTERS,status:'all'}); h.q.read[1].reject(new Error('x')); await tick(); assert.match(h.calls.announce.at(-1)[1],/Не удалось применить фильтр/);});
test('plain refresh failure announces only refresh warning',async()=>{const h=harness(); h.rt.enter(); h.q.read[0].resolve([row(1)]); await tick(); h.rt.read('refresh',DEFAULT_PURCHASE_FILTERS); h.q.read[1].reject(new Error('x')); await tick(); assert.match(h.calls.announce.at(-1)[1],/Не удалось обновить список/);});
test('reconciliation failure announces only reconciliation warning',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.lifecycle.state.needsReconciliation=true; h.lifecycle.state.reconciliationOperationId=7; h.rt.reconcile(); h.q.read[0].reject(new Error('x')); await tick(); assert.match(h.calls.announce[0][1],/Не удалось сверить список/);});
test('invalid DTO announces only invalid-response error',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.update(1,{}); h.q.update[0].resolve(row(2)); await tick(); assert.match(h.calls.announce[0][1],/неожиданный ответ/);});
test('detached settlement announces nothing',async()=>{const h=harness(); h.lifecycle.state.snapshot={items:[row(1)],filters:DEFAULT_PURCHASE_FILTERS,loaded:true}; h.rt.update(1,{}); h.setOwns(false); h.rt.leave(); h.q.update[0].resolve(row(1)); await tick(); assert.equal(h.calls.announce.length,0);});
test('neutral detached render does not announce repeatedly',()=>{const h=harness(); h.lifecycle.state.detachedMutation={requestId:1,kind:'update',routeGeneration:1,suggestionId:1,operationId:1}; h.rt.enter(); h.rt.enter(); assert.equal(h.calls.announce.length,0);});

test('reference ingredient success uses controller request',async()=>{const st=createInitialPurchaseReferenceState(); const d=deferred(); const c=createPurchaseSuggestionsReferenceDataController(st,{loadIngredients:()=>d.promise,loadPackaging:()=>Promise.resolve([]),ownsRoute:()=>true,render:()=>{}}); c.startIngredient(); d.resolve([{id:1}]); await tick(); assert.equal(st.ingredientsLoaded,true);});
test('reference packaging success uses controller request',async()=>{const st=createInitialPurchaseReferenceState(); const d=deferred(); const c=createPurchaseSuggestionsReferenceDataController(st,{loadIngredients:()=>Promise.resolve([]),loadPackaging:()=>d.promise,ownsRoute:()=>true,render:()=>{}}); c.startPackaging(); d.resolve([{id:1}]); await tick(); assert.equal(st.packagingLoaded,true);});
test('reference ingredient failure preserves packaging success',async()=>{const st=createInitialPurchaseReferenceState(); const di=deferred(), dp=deferred(); const c=createPurchaseSuggestionsReferenceDataController(st,{loadIngredients:()=>di.promise,loadPackaging:()=>dp.promise,ownsRoute:()=>true,render:()=>{}}); c.ensure('all'); di.reject(new Error('x')); dp.resolve([{id:1}]); await tick(); assert.deepEqual([st.ingredientsLoaded,st.packagingLoaded],[false,true]);});
test('reference packaging failure preserves ingredient success',async()=>{const st=createInitialPurchaseReferenceState(); const di=deferred(), dp=deferred(); const c=createPurchaseSuggestionsReferenceDataController(st,{loadIngredients:()=>di.promise,loadPackaging:()=>dp.promise,ownsRoute:()=>true,render:()=>{}}); c.ensure('all'); di.resolve([{id:1}]); dp.reject(new Error('x')); await tick(); assert.deepEqual([st.ingredientsLoaded,st.packagingLoaded],[true,false]);});
test('stale ingredient success after route leave is ignored',async()=>{const st=createInitialPurchaseReferenceState(); const d=deferred(); let renders=0; const c=createPurchaseSuggestionsReferenceDataController(st,{loadIngredients:()=>d.promise,loadPackaging:()=>Promise.resolve([]),ownsRoute:()=>true,render:()=>{renders++}}); c.startIngredient(); c.leaveRoute(); d.resolve([{id:1}]); await tick(); assert.equal(st.ingredientsLoaded,false);});
test('stale packaging failure after route leave is ignored',async()=>{const st=createInitialPurchaseReferenceState(); const d=deferred(); const c=createPurchaseSuggestionsReferenceDataController(st,{loadIngredients:()=>Promise.resolve([]),loadPackaging:()=>d.promise,ownsRoute:()=>true,render:()=>{}}); c.startPackaging(); c.leaveRoute(); d.reject(new Error('x')); await tick(); assert.equal(st.packagingError,'');});
test('older ingredient response cannot overwrite newer response',async()=>{const st=createInitialPurchaseReferenceState(); const d1=deferred(), d2=deferred(); let n=0; const c=createPurchaseSuggestionsReferenceDataController(st,{loadIngredients:()=>++n===1?d1.promise:d2.promise,loadPackaging:()=>Promise.resolve([]),ownsRoute:()=>true,render:()=>{}}); c.startIngredient(); st.ingredientRequest=null; c.startIngredient(); d2.resolve([{id:2}]); d1.resolve([{id:1}]); await tick(); assert.equal(st.ingredients[0].id,2);});
test('cached reference data is not unnecessarily reloaded',async()=>{const st=createInitialPurchaseReferenceState(); st.ingredientsLoaded=true; let calls=0; const c=createPurchaseSuggestionsReferenceDataController(st,{loadIngredients:()=>{calls++;return Promise.resolve([])},loadPackaging:()=>Promise.resolve([]),ownsRoute:()=>true,render:()=>{}}); c.startIngredient(); assert.equal(calls,0);});
test('empty ingredient catalog is ready state',async()=>{const st=createInitialPurchaseReferenceState(); const c=createPurchaseSuggestionsReferenceDataController(st,{loadIngredients:()=>Promise.resolve([]),loadPackaging:()=>Promise.resolve([]),ownsRoute:()=>true,render:()=>{}}); c.startIngredient(); await tick(); assert.equal(c.selectedCatalogEmpty('ingredient'),true);});
test('manual submit disabled until selected catalog is ready',()=>{const st=createInitialPurchaseReferenceState(); const c=createPurchaseSuggestionsReferenceDataController(st,{loadIngredients:()=>Promise.resolve([]),loadPackaging:()=>Promise.resolve([]),ownsRoute:()=>true,render:()=>{}}); assert.equal(c.selectedCatalogReady('ingredient'),false);});

test('two reload controls both receive handlers',()=>{let calls=0; const a=ctl(),b=ctl(); bindPurchaseSuggestionControls(fakeRoot({'[data-action="reload-purchase-suggestions"]':[a,b]}),{reload:()=>calls++}); a.click(); b.click(); assert.equal(calls,2);});
test('two reset controls both receive handlers',()=>{let calls=0; const a=ctl(),b=ctl(); bindPurchaseSuggestionControls(fakeRoot({'[data-action="reset-purchase-filters"]':[a,b]}),{resetFilters:()=>calls++}); a.click(); b.click(); assert.equal(calls,2);});
test('all rendered edit controls are bound',()=>{const ids=[]; const a=ctl({id:'1'}),b=ctl({id:'2'}); bindPurchaseSuggestionControls(fakeRoot({'[data-action="edit-purchase-suggestion"]':[a,b]}),{edit:id=>ids.push(id)}); a.click(); b.click(); assert.deepEqual(ids,[1,2]);});
test('all rendered mark controls are bound',()=>{const ids=[]; const a=ctl({id:'1'}),b=ctl({id:'2'}); bindPurchaseSuggestionControls(fakeRoot({'[data-action="mark-purchase-suggestion-purchased"]':[a,b]}),{markPurchased:id=>ids.push(id)}); a.click(); b.click(); assert.deepEqual(ids,[1,2]);});
test('all rendered dismiss controls are bound',()=>{const ids=[]; const a=ctl({id:'1'}),b=ctl({id:'2'}); bindPurchaseSuggestionControls(fakeRoot({'[data-action="dismiss-purchase-suggestion"]':[a,b]}),{dismiss:id=>ids.push(id)}); a.click(); b.click(); assert.deepEqual(ids,[1,2]);});
test('zero controls is safe',()=>{assert.doesNotThrow(()=>bindPurchaseSuggestionControls(fakeRoot({}),{reload:()=>{throw new Error('no')}}));});
test('disabled control does not invoke callback',()=>{let calls=0; const a=ctl({},true); bindPurchaseSuggestionControls(fakeRoot({'[data-action="regenerate-purchase-suggestions"]':[a]}),{regenerate:()=>calls++}); a.click(); assert.equal(calls,0);});
test('rapid duplicate reload clicks result in one accepted lifecycle request',()=>{const h=harness(); const a=ctl(),b=ctl(); bindPurchaseSuggestionControls(fakeRoot({'[data-action="reload-purchase-suggestions"]':[a,b]}),{reload:()=>h.rt.read('refresh',DEFAULT_PURCHASE_FILTERS)}); a.click(); b.click(); assert.equal(h.calls.read.length,1);});
test('rerendered controls use only current production binding root',()=>{let calls=0; const old=ctl(), fresh=ctl(); bindPurchaseSuggestionControls(fakeRoot({'[data-action="reload-purchase-suggestions"]':[fresh]}),{reload:()=>calls++}); old.click(); fresh.click(); assert.equal(calls,1);});
