export type AlertStatus = 'open' | 'resolved' | 'dismissed';
export type AlertStatusFilter = AlertStatus | 'all';
export type AlertFilters<TType extends string = string> = { status: AlertStatusFilter; type: TType | ''; search: string };
export type AlertLike<TType extends string = string> = { id: number; type: TType; status: AlertStatus; message: string; recommended_action: string; related_entity_type: string; related_entity_id: number };
export type AlertGenerationLike = { created_count: number; updated_count: number; resolved_count: number; open_count: number };
export type ReadKind = 'initial' | 'refresh' | 'filter' | 'regeneration-refresh';
export type MutationKind = 'regenerate' | 'resolve' | 'dismiss';
export type AnnouncementKind = 'none' | 'polite' | 'assertive';
export type FeedbackTone = 'none' | 'success' | 'warning' | 'error';
export type FocusKind = 'previous' | 'alert-heading' | 'main-heading' | 'action' | 'list-region' | 'live-region';
export type FocusCandidate = { key: string; kind: FocusKind; enabled: boolean; attached: boolean; hidden?: boolean };
export type StartResult = { accepted: boolean; requestId: number; routeGeneration: number; filters: AlertFilters; reason?: string };
export type FinishResult = { accepted: boolean; present: boolean; announcement: AnnouncementKind; message: string; focusKey: string | null; settledDetached?: boolean };

type ReadOwner = { id: number; kind: ReadKind; routeGeneration: number; filters: AlertFilters } | null;
type MutationOwner = { id: number; kind: MutationKind; routeGeneration: number; alertId?: number; previousFocusKey?: string | null } | null;
export type DetachedAlertMutation = { requestId: number; kind: MutationKind; routeGeneration: number; alertId: number | null; previousFocusKey: string | null };
export type AlertsSnapshot<TAlert extends AlertLike = AlertLike> = { items: TAlert[]; filters: AlertFilters; loaded: boolean };
export type AlertsLifecycleState<TAlert extends AlertLike = AlertLike> = {
  routeGeneration: number; snapshot: AlertsSnapshot<TAlert> | null; read: ReadOwner; mutation: MutationOwner; detachedMutation: DetachedAlertMutation | null; lastGeneration: AlertGenerationLike | null;
  feedback: { tone: FeedbackTone; message: string; refreshWarning: string; mutationError: string };
  pendingFilters: AlertFilters | null; search: string; reentryNeedsReconcile: boolean;
};

export const ALERT_MUTATION_UNCERTAIN_MESSAGE = 'Не удалось подтвердить результат обновления алертов. Обновите список перед повторным действием.';
export const ALERT_ACTION_UNCERTAIN_MESSAGE = 'Не удалось подтвердить результат действия с алертом. Обновите список перед повторным действием.';
export const ALERT_INVALID_RESPONSE_MESSAGE = 'Получен неожиданный ответ для другого алерта. Обновите список перед повторным действием.';
export const ALERT_REGENERATION_REFRESH_WARNING_ANNOUNCEMENT = 'Алерты обновлены, но список не удалось перечитать. Показаны последние загруженные данные.';
const DEFAULT_FILTERS: AlertFilters = { status: 'open', type: '', search: '' };

export function cloneFilters(filters: AlertFilters): AlertFilters { return { status: filters.status, type: filters.type, search: filters.search }; }
export function sameServerFilters(a: AlertFilters, b: AlertFilters) { return a.status === b.status && a.type === b.type; }
export function sameFilters(a: AlertFilters, b: AlertFilters) { return sameServerFilters(a, b) && a.search === b.search; }
export function alertBelongsToServerFilters(alert: AlertLike, filters: AlertFilters) { return (filters.status === 'all' || alert.status === filters.status) && (!filters.type || alert.type === filters.type); }

export class AlertsFeedbackLifecycle<TAlert extends AlertLike = AlertLike> {
  private readId = 0; private mutationId = 0;
  readonly state: AlertsLifecycleState<TAlert> = { routeGeneration: 0, snapshot: null, read: null, mutation: null, detachedMutation: null, lastGeneration: null, feedback: { tone: 'none', message: '', refreshWarning: '', mutationError: '' }, pendingFilters: null, search: '', reentryNeedsReconcile: false };
  enterRoute() { const hadRead = Boolean(this.state.read); this.state.routeGeneration += 1; if (hadRead) { this.readId += 1; this.state.read = null; this.state.pendingFilters = null; this.state.reentryNeedsReconcile = true; } return this.state.routeGeneration; }
  leaveRoute() { if (this.state.mutation && !this.state.detachedMutation) { const m = this.state.mutation; this.state.detachedMutation = { requestId: m.id, kind: m.kind, routeGeneration: m.routeGeneration, alertId: m.alertId ?? null, previousFocusKey: m.previousFocusKey ?? null }; this.state.mutation = null; this.state.pendingFilters = null; } this.state.routeGeneration += 1; return this.state.routeGeneration; }
  ownsRoute(routeGeneration: number) { return routeGeneration === this.state.routeGeneration; }
  displayedFilters(): AlertFilters { return this.state.snapshot ? { ...this.state.snapshot.filters, search: this.state.search } : { ...DEFAULT_FILTERS, search: this.state.search }; }
  activeServerOperation() { return Boolean(this.state.read || this.state.mutation || this.state.detachedMutation); }
  clearTransient() { this.state.feedback = { tone: 'none', message: '', refreshWarning: '', mutationError: '' }; }
  hasPendingReconciliation() { return this.state.reentryNeedsReconcile; }
  startReconciliationRead(kind: ReadKind, filters: AlertFilters, routeGeneration = this.state.routeGeneration): StartResult { if (!this.state.reentryNeedsReconcile || this.activeServerOperation()) return { accepted: false, requestId: this.readId, routeGeneration, filters: cloneFilters(filters), reason: 'busy' }; const started = this.startRead(kind, filters, routeGeneration); if (started.accepted) this.state.reentryNeedsReconcile = false; return started; }
  startRead(kind: ReadKind, filters: AlertFilters, routeGeneration = this.state.routeGeneration): StartResult { if (this.activeServerOperation()) return { accepted: false, requestId: this.readId, routeGeneration, filters: cloneFilters(filters), reason: 'busy' }; const requestId = ++this.readId; const captured = cloneFilters(filters); if (kind !== 'regeneration-refresh') this.clearTransient(); this.state.read = { id: requestId, kind, routeGeneration, filters: captured }; this.state.pendingFilters = captured; return { accepted: true, requestId, routeGeneration, filters: captured }; }
  finishReadSuccess(requestId: number, routeGeneration: number, filters: AlertFilters, items: TAlert[]): FinishResult { const owner = this.state.read; if (!owner || owner.id !== requestId || !sameFilters(owner.filters, filters)) return done(false); const present = this.ownsRoute(routeGeneration) && owner.routeGeneration === routeGeneration; this.state.snapshot = { items: [...items], filters: cloneFilters(filters), loaded: true }; this.state.read = null; this.state.pendingFilters = null; this.state.feedback.mutationError = ''; this.state.feedback.refreshWarning = ''; const explicit = owner.kind === 'refresh' || owner.kind === 'filter'; if (owner.kind !== 'regeneration-refresh') { this.state.feedback.tone = present && explicit ? 'success' : 'none'; this.state.feedback.message = present && explicit ? 'Список алертов обновлён.' : ''; } return done(true, present, present && explicit ? 'polite' : 'none', this.state.feedback.message); }
  finishReadFailure(requestId: number, routeGeneration: number, filters: AlertFilters): FinishResult { const owner = this.state.read; if (!owner || owner.id !== requestId || !sameFilters(owner.filters, filters)) return done(false); const present = this.ownsRoute(routeGeneration) && owner.routeGeneration === routeGeneration; const had = Boolean(this.state.snapshot); this.state.read = null; this.state.pendingFilters = null; if (!present) this.state.reentryNeedsReconcile = true; if (owner.kind !== 'regeneration-refresh') this.state.feedback.message = ''; if (present) { if (had) { this.state.feedback.tone = 'warning'; this.state.feedback.refreshWarning = 'Не удалось обновить список алертов. Показаны последние успешно загруженные данные — они могут быть устаревшими.'; } else { this.state.feedback.tone = 'error'; this.state.feedback.mutationError = 'Не удалось загрузить алерты. Проверьте, что локальное приложение запущено, и попробуйте снова.'; } } return done(true, present, present ? 'assertive' : 'none', had ? this.state.feedback.refreshWarning : this.state.feedback.mutationError); }
  startMutation(kind: MutationKind, routeGeneration = this.state.routeGeneration, alertId?: number, previousFocusKey?: string | null): StartResult { if (this.activeServerOperation() || (kind === 'regenerate' && !this.state.snapshot)) return { accepted: false, requestId: this.mutationId, routeGeneration, filters: this.displayedFilters(), reason: 'busy' }; const requestId = ++this.mutationId; this.clearTransient(); this.state.mutation = { id: requestId, kind, routeGeneration, alertId, previousFocusKey }; return { accepted: true, requestId, routeGeneration, filters: this.displayedFilters() }; }
  finishMutationFailure(requestId: number, routeGeneration: number, message?: string): FinishResult { const owner = this.state.mutation; if (!owner || owner.id !== requestId) return done(false); const present = this.ownsRoute(routeGeneration) && owner.routeGeneration === routeGeneration; this.state.mutation = null; if (!present) this.state.reentryNeedsReconcile = true; if (present) { this.state.feedback.tone = 'error'; this.state.feedback.mutationError = message || (owner.kind === 'regenerate' ? ALERT_MUTATION_UNCERTAIN_MESSAGE : ALERT_ACTION_UNCERTAIN_MESSAGE); } return done(true, present, present ? 'assertive' : 'none', this.state.feedback.mutationError); }
  finishRegenerationSuccess(requestId: number, routeGeneration: number, result: AlertGenerationLike): FinishResult { const owner = this.state.mutation; if (!owner || owner.id !== requestId || owner.kind !== 'regenerate') return done(false); const present = this.ownsRoute(routeGeneration) && owner.routeGeneration === routeGeneration; this.state.mutation = null; this.state.lastGeneration = result; if (!present) this.state.reentryNeedsReconcile = true; if (present) { this.state.feedback.tone = 'success'; this.state.feedback.message = `Алерты обновлены: новых — ${result.created_count}, обновлено — ${result.updated_count}, решено автоматически — ${result.resolved_count}, открытых — ${result.open_count}.`; } return done(true, present, present ? 'polite' : 'none', this.state.feedback.message); }
  applyMutationResponse(requestId: number, routeGeneration: number, expectedAlertId: number, action: 'resolve'|'dismiss', response: TAlert): FinishResult { const owner = this.state.mutation; if (!owner || owner.id !== requestId) return done(false); if (owner.kind !== action || owner.alertId !== expectedAlertId || response.id !== expectedAlertId) return this.finishInvalidMutationResponse(requestId, routeGeneration); const present = this.ownsRoute(routeGeneration) && owner.routeGeneration === routeGeneration; this.state.mutation = null; this.applyAuthoritativeAlert(expectedAlertId, response); if (!present) this.state.reentryNeedsReconcile = true; if (present) { this.state.feedback.tone = 'success'; this.state.feedback.message = action === 'resolve' ? 'Алерт отмечен решённым.' : 'Алерт скрыт.'; } return done(true, present, present ? 'polite' : 'none', this.state.feedback.message); }
  finishInvalidMutationResponse(requestId: number, routeGeneration: number): FinishResult { const owner = this.state.mutation; if (!owner || owner.id !== requestId) return done(false); const present = this.ownsRoute(routeGeneration) && owner.routeGeneration === routeGeneration; this.state.mutation = null; if (!present) this.state.reentryNeedsReconcile = true; if (present) { this.state.feedback.tone = 'error'; this.state.feedback.mutationError = ALERT_INVALID_RESPONSE_MESSAGE; this.state.feedback.message = ''; this.state.feedback.refreshWarning = ''; } return done(true, present, present ? 'assertive' : 'none', this.state.feedback.mutationError); }
  settleDetachedActionSuccess(requestId: number, action: 'resolve'|'dismiss', expectedAlertId: number, response: TAlert): FinishResult { const owner = this.state.detachedMutation; if (!this.detachedMatches(requestId, action, expectedAlertId)) return done(false); this.state.detachedMutation = null; this.state.reentryNeedsReconcile = true; if (response.id !== owner!.alertId) return done(true, false, 'none', '', null, true); this.applyAuthoritativeAlert(expectedAlertId, response); return done(true, false, 'none', '', null, true); }
  settleDetachedRegenerationSuccess(requestId: number, result: AlertGenerationLike): FinishResult { if (!this.detachedMatches(requestId, 'regenerate', null)) return done(false); this.state.detachedMutation = null; this.state.lastGeneration = result; this.state.reentryNeedsReconcile = true; return done(true, false, 'none', '', null, true); }
  settleDetachedMutationFailure(requestId: number, kind: MutationKind, alertId: number | null = null): FinishResult { if (!this.detachedMatches(requestId, kind, alertId)) return done(false); this.state.detachedMutation = null; this.state.reentryNeedsReconcile = true; return done(true, false, 'none', '', null, true); }
  private detachedMatches(requestId: number, kind: MutationKind, alertId: number | null) { const owner = this.state.detachedMutation; return Boolean(owner && owner.requestId === requestId && owner.kind === kind && owner.alertId === alertId); }
  private applyAuthoritativeAlert(expectedAlertId: number, response: TAlert) { if (!this.state.snapshot) return; const filters = this.state.snapshot.filters; const next = this.state.snapshot.items.filter((a) => a.id !== expectedAlertId); if (alertBelongsToServerFilters(response, filters)) { const index = this.state.snapshot.items.findIndex((a) => a.id === expectedAlertId); next.splice(index >= 0 ? index : next.length, 0, response); } this.state.snapshot = { ...this.state.snapshot, items: next }; }
  setSearch(search: string) { this.state.search = search; }
}
function done(accepted: boolean, present = false, announcement: AnnouncementKind = 'none', message = '', focusKey: string | null = null, settledDetached = false): FinishResult { return { accepted, present, announcement, message, focusKey, settledDetached }; }

export function alertsPresentation<TAlert extends AlertLike>(state: AlertsLifecycleState<TAlert>, search = state.search) { const hasSnapshot = Boolean(state.snapshot); const busy = Boolean(state.read || state.mutation || state.detachedMutation); const initialLoading = !hasSnapshot && state.read?.kind === 'initial'; const initialError = !hasSnapshot && state.feedback.tone === 'error'; return { canShowSnapshot: hasSnapshot, initialLoading, initialError, staleWarning: state.feedback.refreshWarning, controlsDisabled: busy, workspaceBusy: busy, searchEnabled: true, reloadCopy: state.read ? (hasSnapshot ? 'Обновляем…' : 'Загружаем…') : 'Загрузить список', regenerateCopy: state.mutation?.kind === 'regenerate' ? 'Обновляем…' : 'Обновить алерты', resolveCopy: state.mutation?.kind === 'resolve' ? 'Отмечаем…' : 'Отметить решённым', dismissCopy: state.mutation?.kind === 'dismiss' ? 'Скрываем…' : 'Скрыть', appliedFilters: state.snapshot ? { ...state.snapshot.filters, search } : { ...DEFAULT_FILTERS, search }, pendingFilters: state.pendingFilters, resultCountSource: hasSnapshot ? 'snapshot' as const : 'none' as const, feedback: state.feedback }; }
export function filterDisplayedAlerts<TAlert extends AlertLike>(items: TAlert[], search: string, text: (alert: TAlert) => string): TAlert[] { const q = search.trim().toLocaleLowerCase(); return q ? items.filter((a) => text(a).toLocaleLowerCase().includes(q)) : items; }
export function selectAlertFocusTarget(ownsPresentation: boolean, previousKey: string | null, alertId: number | null, candidates: FocusCandidate[]): string | null { if (!ownsPresentation) return null; const usable = (c?: FocusCandidate) => Boolean(c && c.attached && c.enabled && !c.hidden && c.kind !== 'live-region'); const previous = previousKey ? candidates.find((c) => c.key === previousKey) : undefined; if (usable(previous)) return previous!.key; if (alertId !== null) { const heading = candidates.find((c) => c.kind === 'alert-heading' && c.key === `alert-${alertId}-heading`); if (usable(heading)) return heading!.key; } const list = candidates.find((c) => c.kind === 'list-region'); if (usable(list)) return list!.key; const main = candidates.find((c) => c.kind === 'main-heading'); if (usable(main)) return main!.key; const action = candidates.find((c) => c.kind === 'action'); if (usable(action)) return action!.key; return null; }
export function bindAlertsActionControls<T extends { addEventListener: (type: 'click', listener: () => void) => void }>(root: { querySelectorAll: (selector: string) => Iterable<T> }, selector: string, callback: () => void): number { const controls = Array.from(root.querySelectorAll(selector)); controls.forEach((control) => control.addEventListener('click', callback)); return controls.length; }
export function transitionAlertsRouteOwnership<T extends { enterRoute: () => number; leaveRoute: () => number }>(lifecycle: T, previousSection: string, nextSection: string): 'entered' | 'left' | 'unchanged' { if (previousSection === 'Алерты' && nextSection !== 'Алерты') { lifecycle.leaveRoute(); return 'left'; } if (previousSection !== 'Алерты' && nextSection === 'Алерты') { lifecycle.enterRoute(); return 'entered'; } return 'unchanged'; }
