import type { PurchaseSuggestionItemType, PurchaseSuggestionLike } from './purchase-suggestions-feedback';

export type ManualPurchaseDraft = { item_type: PurchaseSuggestionItemType; item_id: string; recommended_quantity: string; unit: string; notes: string };
export type EditPurchaseDraft = { recommended_quantity: string; unit: string; notes: string };
export type PurchaseSuggestionFormState = { showManualForm: boolean; manualForm: ManualPurchaseDraft; editingSuggestionId: number | null; editForm: EditPurchaseDraft };
export function emptyManualPurchaseDraft(): ManualPurchaseDraft { return { item_type: 'ingredient', item_id: '', recommended_quantity: '', unit: 'g', notes: '' }; }
export function emptyEditPurchaseDraft(): EditPurchaseDraft { return { recommended_quantity: '', unit: '', notes: '' }; }
export function manualDraftMatchesPayload(draft: ManualPurchaseDraft, payload: { item_type: PurchaseSuggestionItemType; item_id: number; recommended_quantity: string; unit: string; notes?: string }) { return draft.item_type === payload.item_type && draft.item_id === String(payload.item_id) && draft.recommended_quantity === payload.recommended_quantity && draft.unit === payload.unit && draft.notes === (payload.notes ?? ''); }
export function editDraftMatchesPayload(draft: EditPurchaseDraft, payload: { recommended_quantity: string; unit: string; notes?: string }) { return draft.recommended_quantity === payload.recommended_quantity && draft.unit === payload.unit && draft.notes === (payload.notes ?? ''); }
export function completeManualPurchaseDraft(state: PurchaseSuggestionFormState, payload: { item_type: PurchaseSuggestionItemType; item_id: number; recommended_quantity: string; unit: string; notes?: string }) { if (!state.showManualForm || !manualDraftMatchesPayload(state.manualForm, payload)) return false; state.showManualForm = false; state.manualForm = emptyManualPurchaseDraft(); return true; }
export function completeEditPurchaseDraft(state: PurchaseSuggestionFormState, id: number, payload: { recommended_quantity: string; unit: string; notes?: string }) { if (state.editingSuggestionId !== id || !editDraftMatchesPayload(state.editForm, payload)) return false; state.editingSuggestionId = null; state.editForm = emptyEditPurchaseDraft(); return true; }
export function tryStartPurchaseSuggestionEdit<T extends PurchaseSuggestionLike>(state: PurchaseSuggestionFormState, item: T | null | undefined) { if (!item || item.status !== 'open') return false; state.editingSuggestionId = item.id; state.editForm = { recommended_quantity: item.recommended_quantity, unit: item.unit, notes: String(item.notes ?? '') }; return true; }
