export type PurchaseSuggestionStatus = 'open' | 'purchased' | 'dismissed' | 'archived';
export type PurchaseSuggestionStatusFilter = PurchaseSuggestionStatus | 'all';
export type PurchaseSuggestionItemType = 'ingredient' | 'packaging';
export type PurchaseSuggestionItemTypeFilter = PurchaseSuggestionItemType | '';
export type PurchaseSuggestionReason = 'below_minimum_stock' | 'insufficient_for_order' | 'predicted_shortage' | 'expiration_replacement' | 'manual';
export type PurchaseSuggestionReasonFilter = PurchaseSuggestionReason | '';
export type PurchaseSuggestionLike = { id:number; item_type:PurchaseSuggestionItemType; item_id:number; item_name_snapshot:string; recommended_quantity:string; unit:string; reason:PurchaseSuggestionReason; status:PurchaseSuggestionStatus; message?:string; notes?:string; [key:string]:unknown };
export type PurchaseSuggestionFilters = { status:PurchaseSuggestionStatusFilter; reason:PurchaseSuggestionReasonFilter; itemType:PurchaseSuggestionItemTypeFilter; search:string };
export type ReadKind = 'initial'|'refresh'|'filter'|'regeneration-refresh'|'reconciliation';
export type MutationKind = 'regenerate'|'create-manual'|'update'|'mark-purchased'|'dismiss';
export type GenerationResult = { created_count:number; updated_count:number; archived_count:number; open_count:number };
export type FeedbackTone = 'none'|'success'|'warning'|'error'|'neutral';
export const DEFAULT_PURCHASE_FILTERS: PurchaseSuggestionFilters = { status:'open', reason:'', itemType:'', search:'' };
export const PURCHASE_INVALID_RESPONSE_MESSAGE = 'Локальное приложение вернуло неожиданный ответ. Список сохранён как был — нажмите «Загрузить список», чтобы сверить данные.';
export const PURCHASE_RECONCILE_MESSAGE = 'Завершаем предыдущее действие и проверяем список…';
export const PURCHASE_REGEN_REFRESH_WARNING = 'Действие выполнено, но список не удалось перечитать. Показан прежний список — нажмите «Загрузить список» для проверки.';
export const PURCHASE_MARKED_MESSAGE = 'Предложение отмечено как купленное. Склад не изменён — внесите приход отдельно, когда товар фактически поступит.';
export type ReadOwner = null | { requestId:number; routeGeneration:number; kind:ReadKind; filters:PurchaseSuggestionFilters; reconciliationOperationId:number|null };
export type MutationOwner = { requestId:number; kind:MutationKind; routeGeneration:number; suggestionId:number|null; expectedItemType?:PurchaseSuggestionItemType; expectedItemId?:number; previousFocusKey?:string|null; operationId:number };
export type Snapshot<T extends PurchaseSuggestionLike> = { items:T[]; filters:PurchaseSuggestionFilters; loaded:true };
export type FinishResult = { accepted:boolean; present:boolean; announcement:'none'|'polite'|'assertive'; focusKey:string|null; settledDetached?:boolean; valid?:boolean; startFollowupRead?:boolean };
export type StartResult = { accepted:boolean; requestId:number; routeGeneration:number; filters:PurchaseSuggestionFilters; kind?:ReadKind; owner?:MutationOwner; reason?:'busy'|'duplicate' };
export type LifecycleState<T extends PurchaseSuggestionLike> = { routeGeneration:number; read:ReadOwner; mutation:MutationOwner|null; detachedMutation:MutationOwner|null; snapshot:Snapshot<T>|null; pendingFilters:PurchaseSuggestionFilters|null; localSearch:string; lastGeneration:GenerationResult|null; feedback:{tone:FeedbackTone; success:string; mutationError:string; refreshWarning:string; neutral:string}; needsReconciliation:boolean; reconciliationOperationId:number|null };
function cloneFilters(f:PurchaseSuggestionFilters):PurchaseSuggestionFilters{return {...f};}
function sameFilters(a:PurchaseSuggestionFilters,b:PurchaseSuggestionFilters){return a.status===b.status&&a.reason===b.reason&&a.itemType===b.itemType;}
function ok(present:boolean, announcement:FinishResult['announcement']='none', focusKey:string|null=null):FinishResult{return {accepted:true,present,announcement,focusKey};}
function reject():FinishResult{return {accepted:false,present:false,announcement:'none',focusKey:null};}
function matchesFilters(item:PurchaseSuggestionLike, filters:PurchaseSuggestionFilters){return (filters.status==='all'||item.status===filters.status)&&(!filters.reason||item.reason===filters.reason)&&(!filters.itemType||item.item_type===filters.itemType);}
function textOf(item:PurchaseSuggestionLike){return [item.item_name_snapshot,item.message,item.notes,item.reason,item.status].join(' ').toLocaleLowerCase('ru-RU');}
export class PurchaseSuggestionsFeedbackLifecycle<T extends PurchaseSuggestionLike = PurchaseSuggestionLike>{
  private readId=0; private mutationId=0; private operationId=0;
  readonly state:LifecycleState<T>={routeGeneration:0,read:null,mutation:null,detachedMutation:null,snapshot:null,pendingFilters:null,localSearch:'',lastGeneration:null,feedback:{tone:'none',success:'',mutationError:'',refreshWarning:'',neutral:''},needsReconciliation:false,reconciliationOperationId:null};
  enterRoute(){this.state.routeGeneration+=1;if(this.state.detachedMutation)this.state.feedback.neutral=PURCHASE_RECONCILE_MESSAGE;return this.state.routeGeneration;}
  leaveRoute(){if(this.state.mutation&&!this.state.detachedMutation){this.state.detachedMutation={...this.state.mutation};this.state.mutation=null;} if(this.state.read){const abandoned=this.state.read; if(this.state.snapshot){this.state.needsReconciliation=true; this.state.reconciliationOperationId=abandoned.reconciliationOperationId ?? ++this.operationId;} this.state.read=null; this.state.pendingFilters=null;} this.state.routeGeneration+=1;return this.state.routeGeneration;}
  displayedFilters(){return this.state.snapshot?cloneFilters(this.state.snapshot.filters):cloneFilters(DEFAULT_PURCHASE_FILTERS);}
  pendingOrDisplayedFilters(){return cloneFilters(this.state.pendingFilters??this.displayedFilters());}
  startRead(kind:ReadKind, filters:PurchaseSuggestionFilters, routeGeneration=this.state.routeGeneration):StartResult{if(this.state.read||this.state.mutation||this.state.detachedMutation)return {accepted:false,requestId:this.readId,routeGeneration,filters:cloneFilters(filters),kind,reason:'busy'}; const owner={requestId:++this.readId,routeGeneration,kind,filters:cloneFilters(filters),reconciliationOperationId:kind==='reconciliation'?this.state.reconciliationOperationId:null}; this.state.read=owner; if(kind==='filter')this.state.pendingFilters=cloneFilters(filters); this.state.feedback.mutationError=''; return {accepted:true,requestId:owner.requestId,routeGeneration,filters:cloneFilters(filters),kind};}
  startReconciliationRead(filters:PurchaseSuggestionFilters, routeGeneration=this.state.routeGeneration):StartResult{if(!this.state.needsReconciliation||this.state.read||this.state.mutation||this.state.detachedMutation)return {accepted:false,requestId:this.readId,routeGeneration,filters:cloneFilters(filters),kind:'reconciliation',reason:'busy'}; return this.startRead('reconciliation',filters,routeGeneration);}
  finishReadSuccess(requestId:number, routeGeneration:number, filters:PurchaseSuggestionFilters, items:T[]):FinishResult{const r=this.state.read;if(!r||r.requestId!==requestId||r.routeGeneration!==routeGeneration||!sameFilters(r.filters,filters))return reject(); const present=routeGeneration===this.state.routeGeneration; this.state.read=null; this.state.snapshot={items:[...items],filters:cloneFilters(filters),loaded:true}; this.state.pendingFilters=null; this.state.feedback.refreshWarning=''; if(r.kind==='reconciliation'&&r.reconciliationOperationId===this.state.reconciliationOperationId){this.state.needsReconciliation=false;this.state.reconciliationOperationId=null;} return ok(present,'none',present&&r.kind==='initial'?'purchases-main-heading':null);}
  finishReadFailure(requestId:number, routeGeneration:number, filters:PurchaseSuggestionFilters):FinishResult{const r=this.state.read;if(!r||r.requestId!==requestId||r.routeGeneration!==routeGeneration||!sameFilters(r.filters,filters))return reject(); const present=routeGeneration===this.state.routeGeneration; this.state.read=null; this.state.pendingFilters=null; if(!this.state.snapshot){this.state.feedback.tone='error';this.state.feedback.mutationError='Не удалось загрузить закупочные предложения. Проверьте локальное приложение и попробуйте снова.';return ok(present,'assertive','purchase-retry');} this.state.feedback.refreshWarning=r.kind==='filter'?'Не удалось применить фильтр. Показан прежний список закупок.':r.kind==='reconciliation'?'Не удалось сверить список после предыдущего действия. Показаны сохранённые данные — попробуйте загрузить список ещё раз.':r.kind==='regeneration-refresh'?PURCHASE_REGEN_REFRESH_WARNING:'Не удалось обновить список закупок. Показаны сохранённые данные.'; this.state.feedback.tone='warning'; return ok(present,'polite',null);}
  startMutation(kind:MutationKind, routeGeneration=this.state.routeGeneration, suggestionId:number|null=null, opts:Partial<MutationOwner>={}):StartResult{if(this.state.mutation||this.state.detachedMutation||this.state.read)return {accepted:false,requestId:this.mutationId,routeGeneration,filters:this.displayedFilters(),reason:'duplicate'}; const owner:MutationOwner={requestId:++this.mutationId,kind,routeGeneration,suggestionId,expectedItemType:opts.expectedItemType,expectedItemId:opts.expectedItemId,previousFocusKey:opts.previousFocusKey??null,operationId:++this.operationId}; this.state.mutation=owner; this.state.feedback={...this.state.feedback,tone:'none',success:'',mutationError:'',neutral:''}; return {accepted:true,requestId:owner.requestId,routeGeneration,filters:this.displayedFilters(),owner};}
  private exact(owner:MutationOwner|null, requestId:number, kind:MutationKind, suggestionId:number|null, itemType?:PurchaseSuggestionItemType, itemId?:number){return Boolean(owner&&owner.requestId===requestId&&owner.kind===kind&&owner.suggestionId===suggestionId&&(itemType===undefined||owner.expectedItemType===itemType)&&(itemId===undefined||owner.expectedItemId===itemId));}
  private makeReconcile(owner:MutationOwner){this.state.needsReconciliation=true;this.state.reconciliationOperationId=owner.operationId;}
  finishMutationFailure(requestId:number, routeGeneration:number, kind?:MutationKind, suggestionId:number|null=null):FinishResult{const o=this.state.mutation;if(!o||o.requestId!==requestId||o.routeGeneration!==routeGeneration||(kind&&o.kind!==kind)||(kind&&o.suggestionId!==suggestionId))return reject(); this.state.mutation=null; this.state.feedback.tone='error'; this.state.feedback.mutationError='Не удалось выполнить действие. Проверьте данные и попробуйте снова.'; return ok(routeGeneration===this.state.routeGeneration,'assertive',o.previousFocusKey??null);}
  settleDetachedFailure(requestId:number, kind:MutationKind, suggestionId:number|null=null):FinishResult{const o=this.state.detachedMutation;if(!this.exact(o,requestId,kind,suggestionId))return reject(); this.state.detachedMutation=null; this.makeReconcile(o!); return {...ok(false),settledDetached:true};}
  finishRegenerationSuccess(requestId:number, routeGeneration:number, result:GenerationResult):FinishResult{const o=this.state.mutation;if(!this.exact(o,requestId,'regenerate',null)||o!.routeGeneration!==routeGeneration)return reject(); this.state.mutation=null; this.state.lastGeneration=result; this.state.feedback.tone='success'; this.state.feedback.success=`Предложения обновлены: новых — ${result.created_count}, обновлено — ${result.updated_count}, перенесено в архив — ${result.archived_count}, открытых — ${result.open_count}.`; return {...ok(routeGeneration===this.state.routeGeneration,'polite','purchase-regenerate'),startFollowupRead:true};}
  settleDetachedRegenerationSuccess(requestId:number,result:GenerationResult):FinishResult{const o=this.state.detachedMutation;if(!this.exact(o,requestId,'regenerate',null))return reject(); this.state.detachedMutation=null; this.state.lastGeneration=result; this.makeReconcile(o!); return {...ok(false),settledDetached:true};}
  applyResponse(requestId:number, routeGeneration:number, kind:Exclude<MutationKind,'regenerate'>, suggestionId:number|null, response:T):FinishResult{const o=this.state.mutation;if(!this.exact(o,requestId,kind,suggestionId)||o!.routeGeneration!==routeGeneration)return reject(); const valid=this.validFor(o!,response); this.state.mutation=null; if(!valid){this.makeReconcile(o!);this.state.feedback.tone='error';this.state.feedback.mutationError=PURCHASE_INVALID_RESPONSE_MESSAGE;return {...ok(routeGeneration===this.state.routeGeneration,'assertive',o!.previousFocusKey??null),valid:false};} this.applyAuthoritative(response); this.afterSuccess(kind,response); return {...ok(routeGeneration===this.state.routeGeneration,'polite',this.focusFor(kind,response)),valid:true};}
  settleDetachedResponse(requestId:number, kind:Exclude<MutationKind,'regenerate'>, suggestionId:number|null, response:T):FinishResult{const o=this.state.detachedMutation;if(!this.exact(o,requestId,kind,suggestionId))return reject(); this.state.detachedMutation=null; if(this.validFor(o!,response))this.applyAuthoritative(response); this.makeReconcile(o!); return {...ok(false),settledDetached:true,valid:this.validFor(o!,response)};}
  private validFor(o:MutationOwner,response:T){if(o.kind==='create-manual')return response.item_type===o.expectedItemType&&response.item_id===o.expectedItemId&&response.reason==='manual'; if(o.suggestionId!==null)return response.id===o.suggestionId; return true;}
  private applyAuthoritative(response:T){if(!this.state.snapshot)return; const filters=this.state.snapshot.filters; const items=this.state.snapshot.items.filter(i=>i.id!==response.id); if(matchesFilters(response,filters))items.push(response); this.state.snapshot={...this.state.snapshot,items};}
  private afterSuccess(kind:MutationKind,response:T){this.state.feedback.tone='success'; this.state.feedback.mutationError=''; if(kind==='create-manual')this.state.feedback.success='Предложение добавлено вручную.'; if(kind==='update')this.state.feedback.success='Предложение обновлено.'; if(kind==='mark-purchased')this.state.feedback.success=PURCHASE_MARKED_MESSAGE; if(kind==='dismiss')this.state.feedback.success='Предложение скрыто. История сохранена.';}
  private focusFor(kind:MutationKind,response:T){if(kind==='create-manual')return `purchase-suggestion-${response.id}`; if(kind==='update')return `purchase-suggestion-${response.id}`; if(kind==='mark-purchased'||kind==='dismiss')return 'purchase-list'; return 'purchases-main-heading';}
  hasPendingReconciliation(){return this.state.needsReconciliation;}
  setSearch(search:string){this.state.localSearch=search;}
}
export function filterPurchaseSuggestions<T extends PurchaseSuggestionLike>(items:T[],search:string):T[]{const s=search.trim().toLocaleLowerCase('ru-RU'); if(!s)return items; return items.filter(i=>textOf(i).includes(s));}
export function purchaseSuggestionsPresentation<T extends PurchaseSuggestionLike>(state:LifecycleState<T>){const busy=Boolean(state.read||state.mutation||state.detachedMutation);return{busy,controlsDisabled:busy,canShowSnapshot:Boolean(state.snapshot),initialLoading:!state.snapshot&&state.read?.kind==='initial',initialError:!state.snapshot&&state.feedback.tone==='error',items:filterPurchaseSuggestions(state.snapshot?.items??[],state.localSearch),appliedFilters:state.snapshot?{...state.snapshot.filters,search:state.localSearch}:{...DEFAULT_PURCHASE_FILTERS,search:state.localSearch},pendingFilters:state.pendingFilters,feedback:state.feedback,reloadCopy:state.read?'Обновляем…':'Загрузить список',regenerateCopy:state.mutation?.kind==='regenerate'?'Обновляем…':'Обновить предложения',manualCopy:state.mutation?.kind==='create-manual'?'Сохраняем…':'Сохранить предложение',updateCopy:state.mutation?.kind==='update'?'Сохраняем…':'Сохранить',markCopy:state.mutation?.kind==='mark-purchased'?'Отмечаем…':'Отметить купленным',dismissCopy:state.mutation?.kind==='dismiss'?'Скрываем…':'Скрыть'};}
